using MagicTheGathering.API.Models;

namespace MagicTheGathering.API.Repositories
{
    public class MockCardRepository : ICardRepository
    {
        public List<Card> cards;

        public MockCardRepository()
        {
            cards = new List<Card>
            {
                new Card { CardId = 0, Name = "Atarka, World Render", ImageUri = "https://cards.scryfall.io/normal/front/7/1/719f172b-f9ad-4960-af66-757eb54147f6.jpg?1683836596", ConvertedManaCost = 7,
                  ManaCost = new ManaCost { Colorless = 1, White = 0, Blue = 0, Black = 0, Red = 1, Green = 1 },
                  CardTypes = new List<CardType> { CardType.LegendaryCreature, CardType.Dragon, },  CardSubTypes = new List<CardSubType> { CardSubType.Dragon, },
                },
                new Card { CardId = 1, Name = "Emmara, Soul of the Accord", ImageUri = "https://cards.scryfall.io/normal/front/e/8/e8510a1e-62ca-462c-b036-d1312729f27d.jpg?1683836594", ConvertedManaCost = 2,
                  ManaCost = new ManaCost { Colorless = 0, White = 1, Blue = 0, Black = 0, Red = 0, Green = 1 },
                  CardTypes = new List<CardType> { CardType.LegendaryCreature, CardType.ElfCleric, },  CardSubTypes = new List<CardSubType> { CardSubType.Elf, CardSubType.Cleric, },
                },
                new Card { CardId = 2, Name = "Gisa and Geralf", ImageUri = "https://cards.scryfall.io/normal/front/4/d/4d8fd87c-caf7-402e-b543-e35ba3007bcb.jpg?1683836591", ConvertedManaCost = 4,
                  ManaCost = new ManaCost { Colorless = 1, White = 0, Blue = 1, Black = 1, Red = 0, Green = 0 },
                  CardTypes = new List<CardType> { CardType.LegendaryCreature, CardType.HumanWizard, },  CardSubTypes = new List<CardSubType> { CardSubType.Human, CardSubType.Wizard, },
                },
                new Card { CardId = 3, Name = "Isperia, Supreme Judge", ImageUri = "https://cards.scryfall.io/normal/front/d/e/de3278de-a045-4290-b05f-3b19e7055091.jpg?1683836628", ConvertedManaCost = 6,
                  ManaCost = new ManaCost { Colorless = 1, White = 2, Blue = 2, Black = 0, Red = 0, Green = 0 },
                  CardTypes = new List<CardType> { CardType.LegendaryCreature, CardType.Sphinx, },  CardSubTypes = new List<CardSubType> { CardSubType.Sphinx, },
                },
                new Card { CardId = 4, Name = "Island", ImageUri = "https://cards.scryfall.io/normal/front/2/3/23e3ed2c-342b-44aa-8e3e-0c53602397c3.jpg?1699045089", ConvertedManaCost = 0,
                  ManaCost = new ManaCost { Colorless = 0, White = 0, Blue = 0, Black = 1, Red = 1, Green = 0 },
                  CardTypes = new List<CardType> { CardType.BasicLand },  CardSubTypes = new List<CardSubType> { CardSubType.Island },
                },
                new Card { CardId = 4, Name = "Mountain", ImageUri = "https://cards.scryfall.io/normal/front/2/3/23e3ed2c-342b-44aa-8e3e-0c53602397c3.jpg?1699045089", ConvertedManaCost = 0,
                  ManaCost = new ManaCost { Colorless = 0, White = 0, Blue = 0, Black = 1, Red = 1, Green = 0 },
                  CardTypes = new List<CardType> { CardType.BasicLand },  CardSubTypes = new List<CardSubType> { CardSubType.Mountain },
                },
                new Card { CardId = 4, Name = "Swamp", ImageUri = "https://cards.scryfall.io/normal/front/2/3/23e3ed2c-342b-44aa-8e3e-0c53602397c3.jpg?1699045089", ConvertedManaCost = 0,
                  ManaCost = new ManaCost { Colorless = 0, White = 0, Blue = 0, Black = 1, Red = 1, Green = 0 },
                  CardTypes = new List<CardType> { CardType.BasicLand },  CardSubTypes = new List<CardSubType> { CardSubType.Swamp },
                },
                new Card { CardId = 4, Name = "Forest", ImageUri = "https://cards.scryfall.io/normal/front/2/3/23e3ed2c-342b-44aa-8e3e-0c53602397c3.jpg?1699045089", ConvertedManaCost = 0,
                  ManaCost = new ManaCost { Colorless = 0, White = 0, Blue = 0, Black = 1, Red = 1, Green = 0 },
                  CardTypes = new List<CardType> { CardType.BasicLand },  CardSubTypes = new List<CardSubType> { CardSubType.Forest },
                },
                new Card { CardId = 4, Name = "Plain", ImageUri = "https://cards.scryfall.io/normal/front/2/3/23e3ed2c-342b-44aa-8e3e-0c53602397c3.jpg?1699045089", ConvertedManaCost = 0,
                  ManaCost = new ManaCost { Colorless = 0, White = 0, Blue = 0, Black = 1, Red = 1, Green = 0 },
                  CardTypes = new List<CardType> { CardType.BasicLand },  CardSubTypes = new List<CardSubType> { CardSubType.Plain },
                },
                new Card { CardId = 9, Name = "Cartographer's Hawk", ImageUri = "https://cards.scryfall.io/normal/front/c/7/c72102e8-3bcf-4164-a41a-43e3cf1b4b72.jpg?1674674056", ConvertedManaCost = 2,
                  ManaCost = new ManaCost { Colorless = 1, White = 1, Blue = 0, Black = 0, Red = 0, Green = 0 },
                  CardTypes = new List<CardType> { CardType.Creature, CardType.Bird, },  CardSubTypes = new List<CardSubType> { CardSubType.Bird, },
                },
                new Card { CardId = 10, Name = "Citywide Bust", ImageUri = "https://cards.scryfall.io/normal/front/c/2/c249e9db-41a7-4da8-99b3-d7854c538713.jpg?1674674065", ConvertedManaCost = 3,
                  ManaCost = new ManaCost { Colorless = 1, White = 2, Blue = 0, Black = 0, Red = 0, Green = 0 },
                  CardTypes = new List<CardType> { CardType.Sorcery, },  CardSubTypes = new List<CardSubType> { },
                },
                new Card { CardId = 11, Name = "Cleansing Nova", ImageUri = "https://cards.scryfall.io/normal/front/3/1/31619741-1899-4503-bc1c-176a3248df86.jpg?1674674073", ConvertedManaCost = 5,
                  ManaCost = new ManaCost { Colorless = 1, White = 2, Blue = 0, Black = 0, Red = 0, Green = 0 },
                  CardTypes = new List<CardType> { CardType.Sorcery, },  CardSubTypes = new List<CardSubType> { },
                },
                new Card { CardId = 12, Name = "Commander's Insignia", ImageUri = "https://cards.scryfall.io/normal/front/1/2/12b2b04b-27d1-4b5d-9bd6-9678f203cf20.jpg?1674674082", ConvertedManaCost = 4,
                  ManaCost = new ManaCost { Colorless = 1, White = 2, Blue = 0, Black = 0, Red = 0, Green = 0 },
                  CardTypes = new List<CardType> { CardType.Enchantment, },  CardSubTypes = new List<CardSubType> { },
                },
                new Card { CardId = 13, Name = "Conclave Tribunal", ImageUri = "https://cards.scryfall.io/normal/front/1/d/1dc26b58-1b10-41a3-8155-bbc8f189de15.jpg?1674674092", ConvertedManaCost = 4,
                  ManaCost = new ManaCost { Colorless = 1, White = 1, Blue = 0, Black = 0, Red = 0, Green = 0 },
                  CardTypes = new List<CardType> { CardType.Enchantment, },  CardSubTypes = new List<CardSubType> { },
                },
                new Card { CardId = 14, Name = "Condemn", ImageUri = "https://cards.scryfall.io/normal/front/8/5/8554c243-b300-47c2-8dbb-f6a054b894f9.jpg?1674674100", ConvertedManaCost = 1,
                  ManaCost = new ManaCost { Colorless = 0, White = 1, Blue = 0, Black = 0, Red = 0, Green = 0 },
                  CardTypes = new List<CardType> { CardType.Instant, },  CardSubTypes = new List<CardSubType> { },
                },
                new Card { CardId = 15, Name = "Crush Contraband", ImageUri = "https://cards.scryfall.io/normal/front/0/b/0bdf1bc0-116e-4fd0-bbc8-1e284b92d7c0.jpg?1674674111", ConvertedManaCost = 4,
                  ManaCost = new ManaCost { Colorless = 1, White = 1, Blue = 0, Black = 0, Red = 0, Green = 0 },
                  CardTypes = new List<CardType> { CardType.Instant, },  CardSubTypes = new List<CardSubType> { },
                },
                new Card { CardId = 16, Name = "Dawn of Hope", ImageUri = "https://cards.scryfall.io/normal/front/a/0/a02540fc-42ee-4f61-99c8-efdd1a70373c.jpg?1674674119", ConvertedManaCost = 2,
                  ManaCost = new ManaCost { Colorless = 1, White = 1, Blue = 0, Black = 0, Red = 0, Green = 0 },
                  CardTypes = new List<CardType> { CardType.Enchantment, },  CardSubTypes = new List<CardSubType> { },
                },
                new Card { CardId = 17, Name = "Devouring Light", ImageUri = "https://cards.scryfall.io/normal/front/a/2/a22f129b-18a6-4328-aa83-1079be811dcf.jpg?1674674128", ConvertedManaCost = 3,
                  ManaCost = new ManaCost { Colorless = 1, White = 2, Blue = 0, Black = 0, Red = 0, Green = 0 },
                  CardTypes = new List<CardType> { CardType.Instant, },  CardSubTypes = new List<CardSubType> { },
                },
                new Card { CardId = 18, Name = "Dictate of Heliod", ImageUri = "https://cards.scryfall.io/normal/front/f/e/fe2f3830-d822-4cb5-a88a-df5c5b9020a4.jpg?1674674137", ConvertedManaCost = 5,
                  ManaCost = new ManaCost { Colorless = 1, White = 2, Blue = 0, Black = 0, Red = 0, Green = 0 },
                  CardTypes = new List<CardType> { CardType.Enchantment, },  CardSubTypes = new List<CardSubType> { },
                },
                new Card { CardId = 19, Name = "Disenchant", ImageUri = "https://cards.scryfall.io/normal/front/d/3/d32a8448-de76-4d1e-a3dd-8fffeab71216.jpg?1674674145", ConvertedManaCost = 2,
                  ManaCost = new ManaCost { Colorless = 1, White = 1, Blue = 0, Black = 0, Red = 0, Green = 0 },
                  CardTypes = new List<CardType> { CardType.Instant, },  CardSubTypes = new List<CardSubType> { },
                },
                new Card { CardId = 20, Name = "Emeria Angel", ImageUri = "https://cards.scryfall.io/normal/front/a/3/a30852be-473c-40f3-98bf-2d48fcde0239.jpg?1674674154", ConvertedManaCost = 4,
                  ManaCost = new ManaCost { Colorless = 1, White = 2, Blue = 0, Black = 0, Red = 0, Green = 0 },
                  CardTypes = new List<CardType> { CardType.Creature, CardType.Angel, },  CardSubTypes = new List<CardSubType> { CardSubType.Angel, },
                },
                new Card { CardId = 21, Name = "Felidar Retreat", ImageUri = "https://cards.scryfall.io/normal/front/7/3/73febb87-d56b-4214-b429-a606f671e992.jpg?1674674163", ConvertedManaCost = 4,
                  ManaCost = new ManaCost { Colorless = 1, White = 1, Blue = 0, Black = 0, Red = 0, Green = 0 },
                  CardTypes = new List<CardType> { CardType.Enchantment, },  CardSubTypes = new List<CardSubType> { },
                },
                new Card { CardId = 22, Name = "Generous Gift", ImageUri = "https://cards.scryfall.io/normal/front/c/d/cd0f77d1-dd28-41c2-a508-4a8c9e3262ef.jpg?1674674172", ConvertedManaCost = 3,
                  ManaCost = new ManaCost { Colorless = 1, White = 1, Blue = 0, Black = 0, Red = 0, Green = 0 },
                  CardTypes = new List<CardType> { CardType.Instant, },  CardSubTypes = new List<CardSubType> { },
                },
                new Card { CardId = 23, Name = "Gideon Jura", ImageUri = "https://cards.scryfall.io/normal/front/d/f/df0d1217-4d83-4292-80e2-f2d86e82aae4.jpg?1674674181", ConvertedManaCost = 5,
                  ManaCost = new ManaCost { Colorless = 1, White = 2, Blue = 0, Black = 0, Red = 0, Green = 0 },
                  CardTypes = new List<CardType> { CardType.LegendaryPlaneswalker, CardType.Gideon, },  CardSubTypes = new List<CardSubType> { CardSubType.Gideon, },
                },
                new Card { CardId = 24, Name = "Hanged Executioner", ImageUri = "https://cards.scryfall.io/normal/front/e/b/eb405cb1-3643-417c-b27f-4b6c3dca3a96.jpg?1674674190", ConvertedManaCost = 3,
                  ManaCost = new ManaCost { Colorless = 1, White = 1, Blue = 0, Black = 0, Red = 0, Green = 0 },
                  CardTypes = new List<CardType> { CardType.Creature, CardType.Spirit, },  CardSubTypes = new List<CardSubType> { CardSubType.Spirit, },
                },
                new Card { CardId = 25, Name = "Hour of Reckoning", ImageUri = "https://cards.scryfall.io/normal/front/9/1/91961188-da2e-4ba5-b938-154719ea0659.jpg?1674674200", ConvertedManaCost = 7,
                  ManaCost = new ManaCost { Colorless = 1, White = 3, Blue = 0, Black = 0, Red = 0, Green = 0 },
                  CardTypes = new List<CardType> { CardType.Sorcery, },  CardSubTypes = new List<CardSubType> { },
                },
                new Card { CardId = 26, Name = "Kangee's Lieutenant", ImageUri = "https://cards.scryfall.io/normal/front/d/0/d0caf32b-ab0e-4207-9aaa-75c19f88cdd9.jpg?1674674210", ConvertedManaCost = 3,
                  ManaCost = new ManaCost { Colorless = 1, White = 1, Blue = 0, Black = 0, Red = 0, Green = 0 },
                  CardTypes = new List<CardType> { CardType.Creature, CardType.BirdSoldier, },  CardSubTypes = new List<CardSubType> { CardSubType.Bird, CardSubType.Soldier, },
                },
                new Card { CardId = 27, Name = "Mentor of the Meek", ImageUri = "https://cards.scryfall.io/normal/front/e/f/ef899443-579e-48df-b933-e0058173f8f6.jpg?1674674223", ConvertedManaCost = 3,
                  ManaCost = new ManaCost { Colorless = 1, White = 1, Blue = 0, Black = 0, Red = 0, Green = 0 },
                  CardTypes = new List<CardType> { CardType.Creature, CardType.HumanSoldier, },  CardSubTypes = new List<CardSubType> { CardSubType.Human, CardSubType.Soldier, },
                },
                new Card { CardId = 28, Name = "Path to Exile", ImageUri = "https://cards.scryfall.io/normal/front/9/5/95761a9f-fea7-4f8f-b3c4-0b4c596c9f04.jpg?1674674233", ConvertedManaCost = 1,
                  ManaCost = new ManaCost { Colorless = 0, White = 1, Blue = 0, Black = 0, Red = 0, Green = 0 },
                  CardTypes = new List<CardType> { CardType.Instant, },  CardSubTypes = new List<CardSubType> { },
                },
                new Card { CardId = 29, Name = "Rally of Wings", ImageUri = "https://cards.scryfall.io/normal/front/6/2/6209f8ce-651a-450d-a7fb-37d09144e70a.jpg?1674674243", ConvertedManaCost = 2,
                  ManaCost = new ManaCost { Colorless = 1, White = 1, Blue = 0, Black = 0, Red = 0, Green = 0 },
                  CardTypes = new List<CardType> { CardType.Instant, },  CardSubTypes = new List<CardSubType> { },
                },
                new Card { CardId = 30, Name = "Remorseful Cleric", ImageUri = "https://cards.scryfall.io/normal/front/9/0/9058aa42-96bb-4a8e-a2b9-a1a0905de99e.jpg?1674674252", ConvertedManaCost = 2,
                  ManaCost = new ManaCost { Colorless = 1, White = 1, Blue = 0, Black = 0, Red = 0, Green = 0 },
                  CardTypes = new List<CardType> { CardType.Creature, CardType.SpiritCleric, },  CardSubTypes = new List<CardSubType> { CardSubType.Spirit, CardSubType.Cleric, },
                },
                new Card { CardId = 31, Name = "Rootborn Defenses", ImageUri = "https://cards.scryfall.io/normal/front/6/4/644c5708-6e1e-4b59-a78e-1d91c181d19f.jpg?1674674260", ConvertedManaCost = 3,
                  ManaCost = new ManaCost { Colorless = 1, White = 1, Blue = 0, Black = 0, Red = 0, Green = 0 },
                  CardTypes = new List<CardType> { CardType.Instant, },  CardSubTypes = new List<CardSubType> { },
                },
                new Card { CardId = 32, Name = "Sephara, Sky's Blade", ImageUri = "https://cards.scryfall.io/normal/front/3/3/33777ebf-bc27-4e87-bdd6-69dfc979b91f.jpg?1674674268", ConvertedManaCost = 7,
                  ManaCost = new ManaCost { Colorless = 1, White = 3, Blue = 0, Black = 0, Red = 0, Green = 0 },
                  CardTypes = new List<CardType> { CardType.LegendaryCreature, CardType.Angel, },  CardSubTypes = new List<CardSubType> { CardSubType.Angel, },
                },
                new Card { CardId = 33, Name = "Soul Snare", ImageUri = "https://cards.scryfall.io/normal/front/0/5/05cde3d4-de11-4f25-ac06-c6ffebc4615d.jpg?1674674277", ConvertedManaCost = 1,
                  ManaCost = new ManaCost { Colorless = 0, White = 1, Blue = 0, Black = 0, Red = 0, Green = 0 },
                  CardTypes = new List<CardType> { CardType.Enchantment, },  CardSubTypes = new List<CardSubType> { },
                },
                new Card { CardId = 34, Name = "Steel-Plume Marshal", ImageUri = "https://cards.scryfall.io/normal/front/d/3/d35353c1-65a9-4ddc-b7c7-f15b93a7f21c.jpg?1674674287", ConvertedManaCost = 5,
                  ManaCost = new ManaCost { Colorless = 1, White = 2, Blue = 0, Black = 0, Red = 0, Green = 0 },
                  CardTypes = new List<CardType> { CardType.Creature, CardType.BirdSoldier, },  CardSubTypes = new List<CardSubType> { CardSubType.Bird, CardSubType.Soldier, },
                },
                new Card { CardId = 35, Name = "Storm Herd", ImageUri = "https://cards.scryfall.io/normal/front/c/d/cd96606b-b6f5-4caf-81c4-1676a1090ae4.jpg?1674674296", ConvertedManaCost = 10,
                  ManaCost = new ManaCost { Colorless = 1, White = 2, Blue = 0, Black = 0, Red = 0, Green = 0 },
                  CardTypes = new List<CardType> { CardType.Sorcery, },  CardSubTypes = new List<CardSubType> { },
                },
                new Card { CardId = 36, Name = "Swords to Plowshares", ImageUri = "https://cards.scryfall.io/normal/front/5/7/57c2632e-5181-43e4-8744-baafb8f7d213.jpg?1674674304", ConvertedManaCost = 1,
                  ManaCost = new ManaCost { Colorless = 0, White = 1, Blue = 0, Black = 0, Red = 0, Green = 0 },
                  CardTypes = new List<CardType> { CardType.Instant, },  CardSubTypes = new List<CardSubType> { },
                },
                new Card { CardId = 37, Name = "True Conviction", ImageUri = "https://cards.scryfall.io/normal/front/e/3/e3afc893-58bb-4620-94e9-ed544e93d830.jpg?1674674314", ConvertedManaCost = 6,
                  ManaCost = new ManaCost { Colorless = 1, White = 3, Blue = 0, Black = 0, Red = 0, Green = 0 },
                  CardTypes = new List<CardType> { CardType.Enchantment, },  CardSubTypes = new List<CardSubType> { },
                },
                new Card { CardId = 38, Name = "Valor in Akros", ImageUri = "https://cards.scryfall.io/normal/front/3/8/3877146c-da55-4edd-8335-be038f4bf620.jpg?1674674323", ConvertedManaCost = 4,
                  ManaCost = new ManaCost { Colorless = 1, White = 1, Blue = 0, Black = 0, Red = 0, Green = 0 },
                  CardTypes = new List<CardType> { CardType.Enchantment, },  CardSubTypes = new List<CardSubType> { },
                },
                new Card { CardId = 39, Name = "Vow of Duty", ImageUri = "https://cards.scryfall.io/normal/front/2/3/2348be2b-2d33-4214-8f80-cf17c9619eb5.jpg?1674674333", ConvertedManaCost = 3,
                  ManaCost = new ManaCost { Colorless = 1, White = 1, Blue = 0, Black = 0, Red = 0, Green = 0 },
                  CardTypes = new List<CardType> { CardType.Enchantment, CardType.Aura, },  CardSubTypes = new List<CardSubType> { CardSubType.Aura, },
                },
                new Card { CardId = 40, Name = "White Sun's Zenith", ImageUri = "https://cards.scryfall.io/normal/front/b/4/b46f1b5a-da71-4723-afc6-4ab2a569311b.jpg?1674674343", ConvertedManaCost = 3,
                  ManaCost = new ManaCost { Colorless = 0, White = 3, Blue = 0, Black = 0, Red = 0, Green = 0 },
                  CardTypes = new List<CardType> { CardType.Instant, },  CardSubTypes = new List<CardSubType> { },
                },
                new Card { CardId = 41, Name = "Aetherize", ImageUri = "https://cards.scryfall.io/normal/front/e/a/ead56c6e-889c-48d9-87bb-9f80e5bac9b3.jpg?1674674352", ConvertedManaCost = 4,
                  ManaCost = new ManaCost { Colorless = 1, White = 0, Blue = 1, Black = 0, Red = 0, Green = 0 },
                  CardTypes = new List<CardType> { CardType.Instant, },  CardSubTypes = new List<CardSubType> { },
                },
                new Card { CardId = 42, Name = "Angler Turtle", ImageUri = "https://cards.scryfall.io/normal/front/0/1/01c029b2-dbe8-477e-9b61-6df666978444.jpg?1674674362", ConvertedManaCost = 7,
                  ManaCost = new ManaCost { Colorless = 1, White = 0, Blue = 2, Black = 0, Red = 0, Green = 0 },
                  CardTypes = new List<CardType> { CardType.Creature, CardType.Turtle, },  CardSubTypes = new List<CardSubType> { CardSubType.Turtle, },
                },
                new Card { CardId = 43, Name = "Bident of Thassa", ImageUri = "https://cards.scryfall.io/normal/front/0/a/0a024104-3d51-438e-9e72-a2e727450b7d.jpg?1674674371", ConvertedManaCost = 4,
                  ManaCost = new ManaCost { Colorless = 1, White = 0, Blue = 2, Black = 0, Red = 0, Green = 0 },
                  CardTypes = new List<CardType> { CardType.LegendaryEnchantmentArtifact, },  CardSubTypes = new List<CardSubType> { },
                },
                new Card { CardId = 44, Name = "Counterspell", ImageUri = "https://cards.scryfall.io/normal/front/5/2/52042404-12db-4914-bfa0-8249a5942088.jpg?1674674379", ConvertedManaCost = 2,
                  ManaCost = new ManaCost { Colorless = 0, White = 0, Blue = 2, Black = 0, Red = 0, Green = 0 },
                  CardTypes = new List<CardType> { CardType.Instant, },  CardSubTypes = new List<CardSubType> { },
                },
                new Card { CardId = 45, Name = "Deep Analysis", ImageUri = "https://cards.scryfall.io/normal/front/2/7/274ceb53-07a4-4def-bbbd-ac48ff4c7eec.jpg?1674674390", ConvertedManaCost = 4,
                  ManaCost = new ManaCost { Colorless = 1, White = 0, Blue = 1, Black = 0, Red = 0, Green = 0 },
                  CardTypes = new List<CardType> { CardType.Sorcery, },  CardSubTypes = new List<CardSubType> { },
                },
                new Card { CardId = 46, Name = "Diluvian Primordial", ImageUri = "https://cards.scryfall.io/normal/front/5/a/5a12f12c-90d0-4abe-afaa-44f9cdda5648.jpg?1674674400", ConvertedManaCost = 7,
                  ManaCost = new ManaCost { Colorless = 1, White = 0, Blue = 2, Black = 0, Red = 0, Green = 0 },
                  CardTypes = new List<CardType> { CardType.Creature, CardType.Avatar, },  CardSubTypes = new List<CardSubType> { CardSubType.Avatar, },
                },
                new Card { CardId = 47, Name = "Distant Melody", ImageUri = "https://cards.scryfall.io/normal/front/2/2/22f71933-5c7b-4e7c-b508-942f04657799.jpg?1674674410", ConvertedManaCost = 4,
                  ManaCost = new ManaCost { Colorless = 1, White = 0, Blue = 1, Black = 0, Red = 0, Green = 0 },
                  CardTypes = new List<CardType> { CardType.Sorcery, },  CardSubTypes = new List<CardSubType> { },
                },
                new Card { CardId = 48, Name = "Eternal Skylord", ImageUri = "https://cards.scryfall.io/normal/front/f/b/fbef216d-da79-4565-a6a3-adf0de8ee5eb.jpg?1674674419", ConvertedManaCost = 5,
                  ManaCost = new ManaCost { Colorless = 1, White = 0, Blue = 1, Black = 0, Red = 0, Green = 0 },
                  CardTypes = new List<CardType> { CardType.Creature, CardType.ZombieWizard, },  CardSubTypes = new List<CardSubType> { CardSubType.Zombie, CardSubType.Wizard, },
                },
                new Card { CardId = 49, Name = "Ever-Watching Threshold", ImageUri = "https://cards.scryfall.io/normal/front/1/f/1fb0d8fa-48d0-4143-b8c4-d3b01a0bd7cc.jpg?1674674429", ConvertedManaCost = 3,
                  ManaCost = new ManaCost { Colorless = 1, White = 0, Blue = 1, Black = 0, Red = 0, Green = 0 },
                  CardTypes = new List<CardType> { CardType.Enchantment, },  CardSubTypes = new List<CardSubType> { },
                },
                new Card { CardId = 50, Name = "Faerie Formation", ImageUri = "https://cards.scryfall.io/normal/front/8/5/854c4251-c07b-4886-ae12-2b3b61ca2807.jpg?1674674438", ConvertedManaCost = 5,
                  ManaCost = new ManaCost { Colorless = 1, White = 0, Blue = 1, Black = 0, Red = 0, Green = 0 },
                  CardTypes = new List<CardType> { CardType.Creature, CardType.Faerie, },  CardSubTypes = new List<CardSubType> { CardSubType.Faerie, },
                },
                new Card { CardId = 51, Name = "Favorable Winds", ImageUri = "https://cards.scryfall.io/normal/front/c/c/cc11f0f5-ecdc-42a7-9f6a-ecdd44dbc0a2.jpg?1674674448", ConvertedManaCost = 2,
                  ManaCost = new ManaCost { Colorless = 1, White = 0, Blue = 1, Black = 0, Red = 0, Green = 0 },
                  CardTypes = new List<CardType> { CardType.Enchantment, },  CardSubTypes = new List<CardSubType> { },
                },
                new Card { CardId = 52, Name = "Geralf's Mindcrusher", ImageUri = "https://cards.scryfall.io/normal/front/5/3/53dcdb62-28d8-4981-8704-1de4309f76bb.jpg?1673560424", ConvertedManaCost = 6,
                  ManaCost = new ManaCost { Colorless = 1, White = 0, Blue = 2, Black = 0, Red = 0, Green = 0 },
                  CardTypes = new List<CardType> { CardType.Creature, CardType.ZombieHorror, },  CardSubTypes = new List<CardSubType> { CardSubType.Zombie, CardSubType.Horror, },
                },
                new Card { CardId = 53, Name = "Gravitational Shift", ImageUri = "https://cards.scryfall.io/normal/front/8/6/86463838-81d0-464d-84ba-37fa1c76bbea.jpg?1673560439", ConvertedManaCost = 5,
                  ManaCost = new ManaCost { Colorless = 1, White = 0, Blue = 2, Black = 0, Red = 0, Green = 0 },
                  CardTypes = new List<CardType> { CardType.Enchantment, },  CardSubTypes = new List<CardSubType> { },
                },
                new Card { CardId = 54, Name = "Inspired Sphinx", ImageUri = "https://cards.scryfall.io/normal/front/2/1/21522dff-8a65-4816-8b6e-b71270fda3cd.jpg?1673560447", ConvertedManaCost = 7,
                  ManaCost = new ManaCost { Colorless = 1, White = 0, Blue = 2, Black = 0, Red = 0, Green = 0 },
                  CardTypes = new List<CardType> { CardType.Creature, CardType.Sphinx, },  CardSubTypes = new List<CardSubType> { CardSubType.Sphinx, },
                },
                new Card { CardId = 55, Name = "Laboratory Drudge", ImageUri = "https://cards.scryfall.io/normal/front/2/a/2a1a8e0c-b3ca-4da3-8a08-25e3048ca1a2.jpg?1674674458", ConvertedManaCost = 4,
                  ManaCost = new ManaCost { Colorless = 1, White = 0, Blue = 1, Black = 0, Red = 0, Green = 0 },
                  CardTypes = new List<CardType> { CardType.Creature, CardType.ZombieHorror, },  CardSubTypes = new List<CardSubType> { CardSubType.Zombie, CardSubType.Horror, },
                },
                new Card { CardId = 56, Name = "Lazotep Plating", ImageUri = "https://cards.scryfall.io/normal/front/2/7/2751f413-22bb-4aed-b196-225a6ba7c794.jpg?1674674469", ConvertedManaCost = 2,
                  ManaCost = new ManaCost { Colorless = 1, White = 0, Blue = 1, Black = 0, Red = 0, Green = 0 },
                  CardTypes = new List<CardType> { CardType.Instant, },  CardSubTypes = new List<CardSubType> { },
                },
                new Card { CardId = 57, Name = "Negate", ImageUri = "https://cards.scryfall.io/normal/front/c/f/cfc1c914-fa52-4492-8dee-0c35bebc3766.jpg?1674674478", ConvertedManaCost = 2,
                  ManaCost = new ManaCost { Colorless = 1, White = 0, Blue = 1, Black = 0, Red = 0, Green = 0 },
                  CardTypes = new List<CardType> { CardType.Instant, },  CardSubTypes = new List<CardSubType> { },
                },
                new Card { CardId = 58, Name = "Sharding Sphinx", ImageUri = "https://cards.scryfall.io/normal/front/2/8/2861e7a8-0cf5-4b65-adf9-5e7863032c9c.jpg?1674674487", ConvertedManaCost = 6,
                  ManaCost = new ManaCost { Colorless = 1, White = 0, Blue = 2, Black = 0, Red = 0, Green = 0 },
                  CardTypes = new List<CardType> { CardType.ArtifactCreature, CardType.Sphinx, },  CardSubTypes = new List<CardSubType> { CardSubType.Sphinx, },
                },
                new Card { CardId = 59, Name = "Sinister Sabotage", ImageUri = "https://cards.scryfall.io/normal/front/c/d/cd8bfe3c-2c47-4a42-bee8-e34619cdbd41.jpg?1674674496", ConvertedManaCost = 3,
                  ManaCost = new ManaCost { Colorless = 1, White = 0, Blue = 2, Black = 0, Red = 0, Green = 0 },
                  CardTypes = new List<CardType> { CardType.Instant, },  CardSubTypes = new List<CardSubType> { },
                },
                new Card { CardId = 60, Name = "Sphinx of Enlightenment", ImageUri = "https://cards.scryfall.io/normal/front/0/c/0c681f35-e584-45a0-aa4d-bc8955ab1a8a.jpg?1674674505", ConvertedManaCost = 6,
                  ManaCost = new ManaCost { Colorless = 1, White = 0, Blue = 2, Black = 0, Red = 0, Green = 0 },
                  CardTypes = new List<CardType> { CardType.Creature, CardType.Sphinx, },  CardSubTypes = new List<CardSubType> { CardSubType.Sphinx, },
                },
                new Card { CardId = 61, Name = "Tide Skimmer", ImageUri = "https://cards.scryfall.io/normal/front/c/5/c5708b3b-103a-40f3-a4bb-73a499277611.jpg?1674674513", ConvertedManaCost = 4,
                  ManaCost = new ManaCost { Colorless = 1, White = 0, Blue = 1, Black = 0, Red = 0, Green = 0 },
                  CardTypes = new List<CardType> { CardType.Creature, CardType.Drake, },  CardSubTypes = new List<CardSubType> { CardSubType.Drake, },
                },
                new Card { CardId = 62, Name = "Warden of Evos Isle", ImageUri = "https://cards.scryfall.io/normal/front/2/e/2efe4dc9-915b-4715-8fff-1862682a7305.jpg?1674674522", ConvertedManaCost = 3,
                  ManaCost = new ManaCost { Colorless = 1, White = 0, Blue = 1, Black = 0, Red = 0, Green = 0 },
                  CardTypes = new List<CardType> { CardType.Creature, CardType.BirdWizard, },  CardSubTypes = new List<CardSubType> { CardSubType.Bird, CardSubType.Wizard, },
                },
                new Card { CardId = 63, Name = "Windreader Sphinx", ImageUri = "https://cards.scryfall.io/normal/front/2/a/2a36def6-60a5-49c7-bb4f-4f0960ab8f3b.jpg?1674674530", ConvertedManaCost = 7,
                  ManaCost = new ManaCost { Colorless = 1, White = 0, Blue = 2, Black = 0, Red = 0, Green = 0 },
                  CardTypes = new List<CardType> { CardType.Creature, CardType.Sphinx, },  CardSubTypes = new List<CardSubType> { CardSubType.Sphinx, },
                },
                new Card { CardId = 64, Name = "Winged Words", ImageUri = "https://cards.scryfall.io/normal/front/7/5/75fc5499-ed62-4de4-a9bc-72b47f72bd2e.jpg?1674674540", ConvertedManaCost = 3,
                  ManaCost = new ManaCost { Colorless = 1, White = 0, Blue = 1, Black = 0, Red = 0, Green = 0 },
                  CardTypes = new List<CardType> { CardType.Sorcery, },  CardSubTypes = new List<CardSubType> { },
                },
                new Card { CardId = 65, Name = "Ambition's Cost", ImageUri = "https://cards.scryfall.io/normal/front/c/5/c56c3800-b6d5-44e8-8797-2d80070fd4d0.jpg?1674674549", ConvertedManaCost = 4,
                  ManaCost = new ManaCost { Colorless = 1, White = 0, Blue = 0, Black = 1, Red = 0, Green = 0 },
                  CardTypes = new List<CardType> { CardType.Sorcery, },  CardSubTypes = new List<CardSubType> { },
                },
                new Card { CardId = 66, Name = "Archfiend of Depravity", ImageUri = "https://cards.scryfall.io/normal/front/0/6/06bd7be3-20cb-4982-94d4-1f879f91654c.jpg?1674674557", ConvertedManaCost = 5,
                  ManaCost = new ManaCost { Colorless = 1, White = 0, Blue = 0, Black = 2, Red = 0, Green = 0 },
                  CardTypes = new List<CardType> { CardType.Creature, CardType.Demon, },  CardSubTypes = new List<CardSubType> { CardSubType.Demon, },
                },
                new Card { CardId = 67, Name = "Army of the Damned", ImageUri = "https://cards.scryfall.io/normal/front/c/d/cd59d5ff-bba3-46fa-a963-f3dff49a2714.jpg?1674674566", ConvertedManaCost = 8,
                  ManaCost = new ManaCost { Colorless = 1, White = 0, Blue = 0, Black = 3, Red = 0, Green = 0 },
                  CardTypes = new List<CardType> { CardType.Sorcery, },  CardSubTypes = new List<CardSubType> { },
                },
                new Card { CardId = 68, Name = "Bloodgift Demon", ImageUri = "https://cards.scryfall.io/normal/front/7/6/76f21afc-bd35-4b9f-8a31-15ef0fe3f0a7.jpg?1674674574", ConvertedManaCost = 5,
                  ManaCost = new ManaCost { Colorless = 1, White = 0, Blue = 0, Black = 2, Red = 0, Green = 0 },
                  CardTypes = new List<CardType> { CardType.Creature, CardType.Demon, },  CardSubTypes = new List<CardSubType> { CardSubType.Demon, },
                },
                new Card { CardId = 69, Name = "Cemetery Reaper", ImageUri = "https://cards.scryfall.io/normal/front/8/2/82daa7af-2621-4b5b-8828-cab382a9f27c.jpg?1674674583", ConvertedManaCost = 3,
                  ManaCost = new ManaCost { Colorless = 1, White = 0, Blue = 0, Black = 2, Red = 0, Green = 0 },
                  CardTypes = new List<CardType> { CardType.Creature, CardType.Zombie, },  CardSubTypes = new List<CardSubType> { CardSubType.Zombie, },
                },
                new Card { CardId = 70, Name = "Champion of the Perished", ImageUri = "https://cards.scryfall.io/normal/front/7/b/7bd59747-57f7-4ed1-baca-c36cb924d303.jpg?1674674593", ConvertedManaCost = 1,
                  ManaCost = new ManaCost { Colorless = 0, White = 0, Blue = 0, Black = 1, Red = 0, Green = 0 },
                  CardTypes = new List<CardType> { CardType.Creature, CardType.Zombie, },  CardSubTypes = new List<CardSubType> { CardSubType.Zombie, },
                },
                new Card { CardId = 71, Name = "Crippling Fear", ImageUri = "https://cards.scryfall.io/normal/front/d/7/d74c3f9b-5df9-4d74-8c27-a2a9966bfe8c.jpg?1674674603", ConvertedManaCost = 4,
                  ManaCost = new ManaCost { Colorless = 1, White = 0, Blue = 0, Black = 2, Red = 0, Green = 0 },
                  CardTypes = new List<CardType> { CardType.Sorcery, },  CardSubTypes = new List<CardSubType> { },
                },
                new Card { CardId = 72, Name = "Cruel Revival", ImageUri = "https://cards.scryfall.io/normal/front/1/c/1c710e19-4cfb-43a1-bd01-fc0007c7426e.jpg?1674674613", ConvertedManaCost = 5,
                  ManaCost = new ManaCost { Colorless = 1, White = 0, Blue = 0, Black = 1, Red = 0, Green = 0 },
                  CardTypes = new List<CardType> { CardType.Instant, },  CardSubTypes = new List<CardSubType> { },
                },
                new Card { CardId = 73, Name = "Curse of Disturbance", ImageUri = "https://cards.scryfall.io/normal/front/f/8/f8ca82ce-64f8-4e52-b8d9-aec6acb562f9.jpg?1674674622", ConvertedManaCost = 3,
                  ManaCost = new ManaCost { Colorless = 1, White = 0, Blue = 0, Black = 1, Red = 0, Green = 0 },
                  CardTypes = new List<CardType> { CardType.Enchantment, CardType.AuraCurse, },  CardSubTypes = new List<CardSubType> { CardSubType.Aura, CardSubType.Curse, },
                },
                new Card { CardId = 74, Name = "Deadly Tempest", ImageUri = "https://cards.scryfall.io/normal/front/d/c/dcf4fb19-db45-4dd6-9479-6fa065e86cb7.jpg?1674674630", ConvertedManaCost = 6,
                  ManaCost = new ManaCost { Colorless = 1, White = 0, Blue = 0, Black = 2, Red = 0, Green = 0 },
                  CardTypes = new List<CardType> { CardType.Sorcery, },  CardSubTypes = new List<CardSubType> { },
                },
                new Card { CardId = 75, Name = "Dredge the Mire", ImageUri = "https://cards.scryfall.io/normal/front/4/1/4194675b-0807-431c-9d47-7e51e5a1dac0.jpg?1674674638", ConvertedManaCost = 4,
                  ManaCost = new ManaCost { Colorless = 1, White = 0, Blue = 0, Black = 1, Red = 0, Green = 0 },
                  CardTypes = new List<CardType> { CardType.Sorcery, },  CardSubTypes = new List<CardSubType> { },
                },
                new Card { CardId = 76, Name = "Feed the Swarm", ImageUri = "https://cards.scryfall.io/normal/front/5/7/57a77cbc-cbe9-44b4-9651-6967a02c7e75.jpg?1674674647", ConvertedManaCost = 2,
                  ManaCost = new ManaCost { Colorless = 1, White = 0, Blue = 0, Black = 1, Red = 0, Green = 0 },
                  CardTypes = new List<CardType> { CardType.Sorcery, },  CardSubTypes = new List<CardSubType> { },
                },
                new Card { CardId = 77, Name = "Fleshbag Marauder", ImageUri = "https://cards.scryfall.io/normal/front/8/4/84c7bed8-5f79-4f59-b7dc-f17167c140de.jpg?1674674656", ConvertedManaCost = 3,
                  ManaCost = new ManaCost { Colorless = 1, White = 0, Blue = 0, Black = 1, Red = 0, Green = 0 },
                  CardTypes = new List<CardType> { CardType.Creature, CardType.ZombieWarrior, },  CardSubTypes = new List<CardSubType> { CardSubType.Zombie, CardSubType.Warrior, },
                },
                new Card { CardId = 78, Name = "Gravespawn Sovereign", ImageUri = "https://cards.scryfall.io/normal/front/e/1/e1241a23-f2da-4920-9383-b5994d7160af.jpg?1674674666", ConvertedManaCost = 6,
                  ManaCost = new ManaCost { Colorless = 1, White = 0, Blue = 0, Black = 2, Red = 0, Green = 0 },
                  CardTypes = new List<CardType> { CardType.Creature, CardType.Zombie, },  CardSubTypes = new List<CardSubType> { CardSubType.Zombie, },
                },
                new Card { CardId = 79, Name = "Gray Merchant of Asphodel", ImageUri = "https://cards.scryfall.io/normal/front/0/1/013ff2e6-07a6-48ec-a0f4-e933f748ad72.jpg?1674674675", ConvertedManaCost = 5,
                  ManaCost = new ManaCost { Colorless = 1, White = 0, Blue = 0, Black = 2, Red = 0, Green = 0 },
                  CardTypes = new List<CardType> { CardType.Creature, CardType.Zombie, },  CardSubTypes = new List<CardSubType> { CardSubType.Zombie, },
                },
                new Card { CardId = 80, Name = "Indulgent Tormentor", ImageUri = "https://cards.scryfall.io/normal/front/f/f/ff621292-fd89-401b-8306-02cd22b3bb60.jpg?1674674685", ConvertedManaCost = 5,
                  ManaCost = new ManaCost { Colorless = 1, White = 0, Blue = 0, Black = 2, Red = 0, Green = 0 },
                  CardTypes = new List<CardType> { CardType.Creature, CardType.Demon, },  CardSubTypes = new List<CardSubType> { CardSubType.Demon, },
                },
                new Card { CardId = 81, Name = "Josu Vess, Lich Knight", ImageUri = "https://cards.scryfall.io/normal/front/4/b/4b7f57cc-3ce3-48fe-85aa-22df749f57e7.jpg?1674674694", ConvertedManaCost = 4,
                  ManaCost = new ManaCost { Colorless = 1, White = 0, Blue = 0, Black = 2, Red = 0, Green = 0 },
                  CardTypes = new List<CardType> { CardType.LegendaryCreature, CardType.ZombieKnight, },  CardSubTypes = new List<CardSubType> { CardSubType.Zombie, CardSubType.Knight, },
                },
                new Card { CardId = 82, Name = "Lazotep Reaver", ImageUri = "https://cards.scryfall.io/normal/front/8/e/8eebe9a9-b25e-4cf6-a438-cbf794d9c791.jpg?1674674702", ConvertedManaCost = 2,
                  ManaCost = new ManaCost { Colorless = 1, White = 0, Blue = 0, Black = 1, Red = 0, Green = 0 },
                  CardTypes = new List<CardType> { CardType.Creature, CardType.ZombieBeast, },  CardSubTypes = new List<CardSubType> { CardSubType.Zombie, CardSubType.Beast, },
                },
                new Card { CardId = 83, Name = "Liliana, Untouched by Death", ImageUri = "https://cards.scryfall.io/normal/front/4/6/462f8951-7305-4607-92af-92f2b866558d.jpg?1674674711", ConvertedManaCost = 4,
                  ManaCost = new ManaCost { Colorless = 1, White = 0, Blue = 0, Black = 2, Red = 0, Green = 0 },
                  CardTypes = new List<CardType> { CardType.LegendaryPlaneswalker, CardType.Liliana, },  CardSubTypes = new List<CardSubType> { CardSubType.Liliana, },
                },
                new Card { CardId = 84, Name = "Liliana's Devotee", ImageUri = "https://cards.scryfall.io/normal/front/e/5/e5be825b-16ea-49eb-8ffa-79af40ce4f98.jpg?1674674720", ConvertedManaCost = 3,
                  ManaCost = new ManaCost { Colorless = 1, White = 0, Blue = 0, Black = 1, Red = 0, Green = 0 },
                  CardTypes = new List<CardType> { CardType.Creature, CardType.HumanWarlock, },  CardSubTypes = new List<CardSubType> { CardSubType.Human, CardSubType.Warlock, },
                },
                new Card { CardId = 85, Name = "Liliana's Mastery", ImageUri = "https://cards.scryfall.io/normal/front/9/9/99833a13-cc77-4fa3-ae3e-def47a30e944.jpg?1674674730", ConvertedManaCost = 5,
                  ManaCost = new ManaCost { Colorless = 1, White = 0, Blue = 0, Black = 2, Red = 0, Green = 0 },
                  CardTypes = new List<CardType> { CardType.Enchantment, },  CardSubTypes = new List<CardSubType> { },
                },
                new Card { CardId = 86, Name = "Liliana's Standard Bearer", ImageUri = "https://cards.scryfall.io/normal/front/7/4/74a77fff-909a-4c6a-88b9-a403f5625135.jpg?1674674738", ConvertedManaCost = 3,
                  ManaCost = new ManaCost { Colorless = 1, White = 0, Blue = 0, Black = 1, Red = 0, Green = 0 },
                  CardTypes = new List<CardType> { CardType.Creature, CardType.ZombieKnight, },  CardSubTypes = new List<CardSubType> { CardSubType.Zombie, CardSubType.Knight, },
                },
                new Card { CardId = 87, Name = "Lord of the Accursed", ImageUri = "https://cards.scryfall.io/normal/front/b/b/bb4e5e8a-ce5d-48a8-99c8-e459c92552cb.jpg?1674674748", ConvertedManaCost = 3,
                  ManaCost = new ManaCost { Colorless = 1, White = 0, Blue = 0, Black = 1, Red = 0, Green = 0 },
                  CardTypes = new List<CardType> { CardType.Creature, CardType.Zombie, },  CardSubTypes = new List<CardSubType> { CardSubType.Zombie, },
                },
                new Card { CardId = 88, Name = "Lotleth Giant", ImageUri = "https://cards.scryfall.io/normal/front/c/3/c3a73aaf-3613-4ffb-ad04-3e22abe11937.jpg?1674674757", ConvertedManaCost = 7,
                  ManaCost = new ManaCost { Colorless = 1, White = 0, Blue = 0, Black = 1, Red = 0, Green = 0 },
                  CardTypes = new List<CardType> { CardType.Creature, CardType.ZombieGiant, },  CardSubTypes = new List<CardSubType> { CardSubType.Zombie, CardSubType.Giant, },
                },
                new Card { CardId = 89, Name = "Loyal Subordinate", ImageUri = "https://cards.scryfall.io/normal/front/5/1/5103b06e-df31-4f02-91f1-849c63ed210e.jpg?1674674765", ConvertedManaCost = 3,
                  ManaCost = new ManaCost { Colorless = 1, White = 0, Blue = 0, Black = 1, Red = 0, Green = 0 },
                  CardTypes = new List<CardType> { CardType.Creature, CardType.Zombie, },  CardSubTypes = new List<CardSubType> { CardSubType.Zombie, },
                },
                new Card { CardId = 90, Name = "Midnight Reaper", ImageUri = "https://cards.scryfall.io/normal/front/0/d/0dc376ef-6c79-4ff1-89ed-61001a6267cc.jpg?1674674774", ConvertedManaCost = 3,
                  ManaCost = new ManaCost { Colorless = 1, White = 0, Blue = 0, Black = 1, Red = 0, Green = 0 },
                  CardTypes = new List<CardType> { CardType.Creature, CardType.ZombieKnight, },  CardSubTypes = new List<CardSubType> { CardSubType.Zombie, CardSubType.Knight, },
                },
                new Card { CardId = 91, Name = "Mire Triton", ImageUri = "https://cards.scryfall.io/normal/front/5/6/56d7e5fa-6521-4a00-afa5-de8867a1192e.jpg?1674674784", ConvertedManaCost = 2,
                  ManaCost = new ManaCost { Colorless = 1, White = 0, Blue = 0, Black = 1, Red = 0, Green = 0 },
                  CardTypes = new List<CardType> { CardType.Creature, CardType.ZombieMerfolk, },  CardSubTypes = new List<CardSubType> { CardSubType.Zombie, CardSubType.Merfolk, },
                },
                new Card { CardId = 92, Name = "Murder", ImageUri = "https://cards.scryfall.io/normal/front/f/7/f7139613-488b-496b-a21d-a577b1426e6f.jpg?1674674792", ConvertedManaCost = 3,
                  ManaCost = new ManaCost { Colorless = 1, White = 0, Blue = 0, Black = 2, Red = 0, Green = 0 },
                  CardTypes = new List<CardType> { CardType.Instant, },  CardSubTypes = new List<CardSubType> { },
                },
                new Card { CardId = 93, Name = "Necromantic Selection", ImageUri = "https://cards.scryfall.io/normal/front/0/7/0710c560-3a40-4f4b-8dd1-e97a15e95dd5.jpg?1674674802", ConvertedManaCost = 7,
                  ManaCost = new ManaCost { Colorless = 1, White = 0, Blue = 0, Black = 3, Red = 0, Green = 0 },
                  CardTypes = new List<CardType> { CardType.Sorcery, },  CardSubTypes = new List<CardSubType> { },
                },
                new Card { CardId = 94, Name = "Necrotic Hex", ImageUri = "https://cards.scryfall.io/normal/front/a/4/a447bd2a-110c-46fa-97db-8b92aade1d1f.jpg?1674674809", ConvertedManaCost = 7,
                  ManaCost = new ManaCost { Colorless = 1, White = 0, Blue = 0, Black = 1, Red = 0, Green = 0 },
                  CardTypes = new List<CardType> { CardType.Sorcery, },  CardSubTypes = new List<CardSubType> { },
                },
                new Card { CardId = 95, Name = "Ob Nixilis Reignited", ImageUri = "https://cards.scryfall.io/normal/front/7/1/71c285f6-1e6b-43b1-9af2-edb68e9cc30e.jpg?1674674817", ConvertedManaCost = 5,
                  ManaCost = new ManaCost { Colorless = 1, White = 0, Blue = 0, Black = 2, Red = 0, Green = 0 },
                  CardTypes = new List<CardType> { CardType.LegendaryPlaneswalker, CardType.Nixilis, },  CardSubTypes = new List<CardSubType> { CardSubType.Nixilis, },
                },
                new Card { CardId = 96, Name = "Open the Graves", ImageUri = "https://cards.scryfall.io/normal/front/1/1/11fedd76-ee35-4a17-8cdb-684414783df9.jpg?1674674826", ConvertedManaCost = 5,
                  ManaCost = new ManaCost { Colorless = 1, White = 0, Blue = 0, Black = 2, Red = 0, Green = 0 },
                  CardTypes = new List<CardType> { CardType.Enchantment, },  CardSubTypes = new List<CardSubType> { },
                },
                new Card { CardId = 97, Name = "Overseer of the Damned", ImageUri = "https://cards.scryfall.io/normal/front/9/6/967f3962-482b-4080-bc65-3add0e34426b.jpg?1674674834", ConvertedManaCost = 7,
                  ManaCost = new ManaCost { Colorless = 1, White = 0, Blue = 0, Black = 2, Red = 0, Green = 0 },
                  CardTypes = new List<CardType> { CardType.Creature, CardType.Demon, },  CardSubTypes = new List<CardSubType> { CardSubType.Demon, },
                },
                new Card { CardId = 98, Name = "Profane Command", ImageUri = "https://cards.scryfall.io/normal/front/d/2/d2ab6949-a0fc-4fe5-ae64-53b53914f34c.jpg?1674674843", ConvertedManaCost = 2,
                  ManaCost = new ManaCost { Colorless = 0, White = 0, Blue = 0, Black = 2, Red = 0, Green = 0 },
                  CardTypes = new List<CardType> { CardType.Sorcery, },  CardSubTypes = new List<CardSubType> { },
                },
                new Card { CardId = 99, Name = "Rakshasa Debaser", ImageUri = "https://cards.scryfall.io/normal/front/1/1/11e16fad-925a-4b59-8612-362f650e09e1.jpg?1674674851", ConvertedManaCost = 6,
                  ManaCost = new ManaCost { Colorless = 1, White = 0, Blue = 0, Black = 2, Red = 0, Green = 0 },
                  CardTypes = new List<CardType> { CardType.Creature, CardType.Demon, },  CardSubTypes = new List<CardSubType> { CardSubType.Demon, },
                },
                new Card { CardId = 100, Name = "Read the Bones", ImageUri = "https://cards.scryfall.io/normal/front/b/6/b6462949-9a13-4f7d-9656-658e7f7f1116.jpg?1674674859", ConvertedManaCost = 3,
                  ManaCost = new ManaCost { Colorless = 1, White = 0, Blue = 0, Black = 1, Red = 0, Green = 0 },
                  CardTypes = new List<CardType> { CardType.Sorcery, },  CardSubTypes = new List<CardSubType> { },
                },
                new Card { CardId = 101, Name = "Reign of the Pit", ImageUri = "https://cards.scryfall.io/normal/front/0/9/098c7cd1-5f20-437d-9b81-f480f3f02833.jpg?1674674867", ConvertedManaCost = 6,
                  ManaCost = new ManaCost { Colorless = 1, White = 0, Blue = 0, Black = 2, Red = 0, Green = 0 },
                  CardTypes = new List<CardType> { CardType.Sorcery, },  CardSubTypes = new List<CardSubType> { },
                },
                new Card { CardId = 102, Name = "Sangromancer", ImageUri = "https://cards.scryfall.io/normal/front/6/c/6c503202-b7e4-4c98-8276-729ace2af390.jpg?1674674875", ConvertedManaCost = 4,
                  ManaCost = new ManaCost { Colorless = 1, White = 0, Blue = 0, Black = 2, Red = 0, Green = 0 },
                  CardTypes = new List<CardType> { CardType.Creature, CardType.VampireShaman, },  CardSubTypes = new List<CardSubType> { CardSubType.Vampire, CardSubType.Shaman, },
                },
                new Card { CardId = 103, Name = "Scourge of Nel Toth", ImageUri = "https://cards.scryfall.io/normal/front/a/c/acd8312a-1dd6-42eb-8908-51b85ceab6e2.jpg?1674674884", ConvertedManaCost = 7,
                  ManaCost = new ManaCost { Colorless = 1, White = 0, Blue = 0, Black = 2, Red = 0, Green = 0 },
                  CardTypes = new List<CardType> { CardType.Creature, CardType.ZombieDragon, },  CardSubTypes = new List<CardSubType> { CardSubType.Zombie, CardSubType.Dragon, },
                },
                new Card { CardId = 104, Name = "Scythe Specter", ImageUri = "https://cards.scryfall.io/normal/front/2/3/232afb53-8799-4d45-a3b5-f29ff5afc0c3.jpg?1674674893", ConvertedManaCost = 6,
                  ManaCost = new ManaCost { Colorless = 1, White = 0, Blue = 0, Black = 2, Red = 0, Green = 0 },
                  CardTypes = new List<CardType> { CardType.Creature, CardType.Specter, },  CardSubTypes = new List<CardSubType> { CardSubType.Specter, },
                },
                new Card { CardId = 105, Name = "Sepulchral Primordial", ImageUri = "https://cards.scryfall.io/normal/front/5/e/5e4064a4-98e6-41e0-b099-ef97c5dd86f6.jpg?1674674902", ConvertedManaCost = 7,
                  ManaCost = new ManaCost { Colorless = 1, White = 0, Blue = 0, Black = 2, Red = 0, Green = 0 },
                  CardTypes = new List<CardType> { CardType.Creature, CardType.Avatar, },  CardSubTypes = new List<CardSubType> { CardSubType.Avatar, },
                },
                new Card { CardId = 106, Name = "Sign in Blood", ImageUri = "https://cards.scryfall.io/normal/front/9/6/96f4824c-61d4-4ffa-904e-c8ae97350704.jpg?1674674910", ConvertedManaCost = 2,
                  ManaCost = new ManaCost { Colorless = 0, White = 0, Blue = 0, Black = 2, Red = 0, Green = 0 },
                  CardTypes = new List<CardType> { CardType.Sorcery, },  CardSubTypes = new List<CardSubType> { },
                },
                new Card { CardId = 107, Name = "Soul Shatter", ImageUri = "https://cards.scryfall.io/normal/front/2/5/25bc7936-4c85-47d5-8ac4-094403bd5edb.jpg?1674674919", ConvertedManaCost = 3,
                  ManaCost = new ManaCost { Colorless = 1, White = 0, Blue = 0, Black = 1, Red = 0, Green = 0 },
                  CardTypes = new List<CardType> { CardType.Instant, },  CardSubTypes = new List<CardSubType> { },
                },
                new Card { CardId = 108, Name = "Spark Reaper", ImageUri = "https://cards.scryfall.io/normal/front/5/3/53e1cff4-efc8-4479-bfe7-a0e4f1614d44.jpg?1674674928", ConvertedManaCost = 3,
                  ManaCost = new ManaCost { Colorless = 1, White = 0, Blue = 0, Black = 1, Red = 0, Green = 0 },
                  CardTypes = new List<CardType> { CardType.Creature, CardType.Zombie, },  CardSubTypes = new List<CardSubType> { CardSubType.Zombie, },
                },
                new Card { CardId = 109, Name = "Syphon Flesh", ImageUri = "https://cards.scryfall.io/normal/front/5/e/5ecbb2b5-2a9d-417e-a73d-9ab21c5308ea.jpg?1674674936", ConvertedManaCost = 5,
                  ManaCost = new ManaCost { Colorless = 1, White = 0, Blue = 0, Black = 1, Red = 0, Green = 0 },
                  CardTypes = new List<CardType> { CardType.Sorcery, },  CardSubTypes = new List<CardSubType> { },
                },
                new Card { CardId = 110, Name = "Syphon Mind", ImageUri = "https://cards.scryfall.io/normal/front/5/9/5987343f-ce72-4a25-8667-571fc0dbb809.jpg?1674674944", ConvertedManaCost = 4,
                  ManaCost = new ManaCost { Colorless = 1, White = 0, Blue = 0, Black = 1, Red = 0, Green = 0 },
                  CardTypes = new List<CardType> { CardType.Sorcery, },  CardSubTypes = new List<CardSubType> { },
                },
                new Card { CardId = 111, Name = "Titan Hunter", ImageUri = "https://cards.scryfall.io/normal/front/7/b/7b7655b2-3367-478e-81b7-d8fca8911c9b.jpg?1674674954", ConvertedManaCost = 5,
                  ManaCost = new ManaCost { Colorless = 1, White = 0, Blue = 0, Black = 1, Red = 0, Green = 0 },
                  CardTypes = new List<CardType> { CardType.Creature, CardType.HumanWarrior, },  CardSubTypes = new List<CardSubType> { CardSubType.Human, CardSubType.Warrior, },
                },
                new Card { CardId = 112, Name = "Unbreathing Horde", ImageUri = "https://cards.scryfall.io/normal/front/9/d/9d656bd0-82e3-4261-b1bb-929beb87d172.jpg?1674674963", ConvertedManaCost = 3,
                  ManaCost = new ManaCost { Colorless = 1, White = 0, Blue = 0, Black = 1, Red = 0, Green = 0 },
                  CardTypes = new List<CardType> { CardType.Creature, CardType.Zombie, },  CardSubTypes = new List<CardSubType> { CardSubType.Zombie, },
                },
                new Card { CardId = 113, Name = "Undead Augur", ImageUri = "https://cards.scryfall.io/normal/front/e/e/ee44589e-2c10-43d6-8151-84b34986e35b.jpg?1674674971", ConvertedManaCost = 2,
                  ManaCost = new ManaCost { Colorless = 0, White = 0, Blue = 0, Black = 2, Red = 0, Green = 0 },
                  CardTypes = new List<CardType> { CardType.Creature, CardType.ZombieWizard, },  CardSubTypes = new List<CardSubType> { CardSubType.Zombie, CardSubType.Wizard, },
                },
                new Card { CardId = 114, Name = "Vampire Nighthawk", ImageUri = "https://cards.scryfall.io/normal/front/5/1/51901ebb-27ba-4dc3-9224-2bd31024c2b7.jpg?1674674978", ConvertedManaCost = 3,
                  ManaCost = new ManaCost { Colorless = 1, White = 0, Blue = 0, Black = 2, Red = 0, Green = 0 },
                  CardTypes = new List<CardType> { CardType.Creature, CardType.VampireShaman, },  CardSubTypes = new List<CardSubType> { CardSubType.Vampire, CardSubType.Shaman, },
                },
                new Card { CardId = 115, Name = "Vampiric Rites", ImageUri = "https://cards.scryfall.io/normal/front/d/a/da2e2548-a6ab-4968-8fb3-c9b212443a81.jpg?1674674987", ConvertedManaCost = 1,
                  ManaCost = new ManaCost { Colorless = 0, White = 0, Blue = 0, Black = 1, Red = 0, Green = 0 },
                  CardTypes = new List<CardType> { CardType.Enchantment, },  CardSubTypes = new List<CardSubType> { },
                },
                new Card { CardId = 116, Name = "Vengeful Dead", ImageUri = "https://cards.scryfall.io/normal/front/e/b/eb020ae5-4e51-4348-a013-f723996b8ad4.jpg?1673561011", ConvertedManaCost = 4,
                  ManaCost = new ManaCost { Colorless = 1, White = 0, Blue = 0, Black = 1, Red = 0, Green = 0 },
                  CardTypes = new List<CardType> { CardType.Creature, CardType.Zombie, },  CardSubTypes = new List<CardSubType> { CardSubType.Zombie, },
                },
                new Card { CardId = 117, Name = "Victimize", ImageUri = "https://cards.scryfall.io/normal/front/6/f/6f5e8449-f643-41b4-977f-45a6f62546d4.jpg?1674674995", ConvertedManaCost = 3,
                  ManaCost = new ManaCost { Colorless = 1, White = 0, Blue = 0, Black = 1, Red = 0, Green = 0 },
                  CardTypes = new List<CardType> { CardType.Sorcery, },  CardSubTypes = new List<CardSubType> { },
                },
                new Card { CardId = 118, Name = "Vizier of the Scorpion", ImageUri = "https://cards.scryfall.io/normal/front/d/b/db9beaff-8253-49d9-b57f-20b8cf14c802.jpg?1674675004", ConvertedManaCost = 3,
                  ManaCost = new ManaCost { Colorless = 1, White = 0, Blue = 0, Black = 1, Red = 0, Green = 0 },
                  CardTypes = new List<CardType> { CardType.Creature, CardType.ZombieWizard, },  CardSubTypes = new List<CardSubType> { CardSubType.Zombie, CardSubType.Wizard, },
                },
                new Card { CardId = 119, Name = "Withered Wretch", ImageUri = "https://cards.scryfall.io/normal/front/f/5/f5ec82d7-b29f-4e38-833d-f9943ecfaec1.jpg?1673561034", ConvertedManaCost = 2,
                  ManaCost = new ManaCost { Colorless = 0, White = 0, Blue = 0, Black = 2, Red = 0, Green = 0 },
                  CardTypes = new List<CardType> { CardType.Creature, CardType.ZombieCleric, },  CardSubTypes = new List<CardSubType> { CardSubType.Zombie, CardSubType.Cleric, },
                },
                new Card { CardId = 120, Name = "Zombie Apocalypse", ImageUri = "https://cards.scryfall.io/normal/front/3/1/31928e60-4758-4d84-ad0a-2a1634cabf39.jpg?1674675013", ConvertedManaCost = 6,
                  ManaCost = new ManaCost { Colorless = 1, White = 0, Blue = 0, Black = 3, Red = 0, Green = 0 },
                  CardTypes = new List<CardType> { CardType.Sorcery, },  CardSubTypes = new List<CardSubType> { },
                },
                new Card { CardId = 121, Name = "Abrade", ImageUri = "https://cards.scryfall.io/normal/front/7/7/778fad36-28d5-488b-bc7a-e60c8646bdc2.jpg?1674675022", ConvertedManaCost = 2,
                  ManaCost = new ManaCost { Colorless = 1, White = 0, Blue = 0, Black = 0, Red = 1, Green = 0 },
                  CardTypes = new List<CardType> { CardType.Instant, },  CardSubTypes = new List<CardSubType> { },
                },
                new Card { CardId = 122, Name = "Akoum Hellkite", ImageUri = "https://cards.scryfall.io/normal/front/c/c/cc2bff9a-b8a4-49a0-8208-9c6ebc56df14.jpg?1674675032", ConvertedManaCost = 6,
                  ManaCost = new ManaCost { Colorless = 1, White = 0, Blue = 0, Black = 0, Red = 2, Green = 0 },
                  CardTypes = new List<CardType> { CardType.Creature, CardType.Dragon, },  CardSubTypes = new List<CardSubType> { CardSubType.Dragon, },
                },
                new Card { CardId = 123, Name = "Blasphemous Act", ImageUri = "https://cards.scryfall.io/normal/front/7/0/70d1135e-ac1e-40f0-b47d-abc5b427ce55.jpg?1674675041", ConvertedManaCost = 9,
                  ManaCost = new ManaCost { Colorless = 1, White = 0, Blue = 0, Black = 0, Red = 1, Green = 0 },
                  CardTypes = new List<CardType> { CardType.Sorcery, },  CardSubTypes = new List<CardSubType> { },
                },
                new Card { CardId = 124, Name = "Brash Taunter", ImageUri = "https://cards.scryfall.io/normal/front/8/6/86766f31-56f3-446e-950c-5238861e1b66.jpg?1674675050", ConvertedManaCost = 5,
                  ManaCost = new ManaCost { Colorless = 1, White = 0, Blue = 0, Black = 0, Red = 1, Green = 0 },
                  CardTypes = new List<CardType> { CardType.Creature, CardType.Goblin, },  CardSubTypes = new List<CardSubType> { CardSubType.Goblin, },
                },
                new Card { CardId = 125, Name = "Chain Reaction", ImageUri = "https://cards.scryfall.io/normal/front/0/6/0609ddd2-1e98-4fe3-855e-c0ba1c365369.jpg?1674675061", ConvertedManaCost = 4,
                  ManaCost = new ManaCost { Colorless = 1, White = 0, Blue = 0, Black = 0, Red = 2, Green = 0 },
                  CardTypes = new List<CardType> { CardType.Sorcery, },  CardSubTypes = new List<CardSubType> { },
                },
                new Card { CardId = 126, Name = "Chaos Warp", ImageUri = "https://cards.scryfall.io/normal/front/0/7/07d3dbce-ef28-4c03-9b7b-92f1caaf1f01.jpg?1674675072", ConvertedManaCost = 3,
                  ManaCost = new ManaCost { Colorless = 1, White = 0, Blue = 0, Black = 0, Red = 1, Green = 0 },
                  CardTypes = new List<CardType> { CardType.Instant, },  CardSubTypes = new List<CardSubType> { },
                },
                new Card { CardId = 127, Name = "Combustible Gearhulk", ImageUri = "https://cards.scryfall.io/normal/front/8/a/8a0d3d7a-6f6f-472e-bd4e-12d9c36b3b16.jpg?1674675080", ConvertedManaCost = 6,
                  ManaCost = new ManaCost { Colorless = 1, White = 0, Blue = 0, Black = 0, Red = 2, Green = 0 },
                  CardTypes = new List<CardType> { CardType.ArtifactCreature, CardType.Construct, },  CardSubTypes = new List<CardSubType> { CardSubType.Construct, },
                },
                new Card { CardId = 128, Name = "Crucible of Fire", ImageUri = "https://cards.scryfall.io/normal/front/a/4/a4cfcb17-6401-4595-82e6-ac1ab2a9e43b.jpg?1674675089", ConvertedManaCost = 4,
                  ManaCost = new ManaCost { Colorless = 1, White = 0, Blue = 0, Black = 0, Red = 1, Green = 0 },
                  CardTypes = new List<CardType> { CardType.Enchantment, },  CardSubTypes = new List<CardSubType> { },
                },
                new Card { CardId = 129, Name = "Demanding Dragon", ImageUri = "https://cards.scryfall.io/normal/front/f/9/f97d0541-f04f-44a6-a20f-4d909ccc90ca.jpg?1674675097", ConvertedManaCost = 5,
                  ManaCost = new ManaCost { Colorless = 1, White = 0, Blue = 0, Black = 0, Red = 2, Green = 0 },
                  CardTypes = new List<CardType> { CardType.Creature, CardType.Dragon, },  CardSubTypes = new List<CardSubType> { CardSubType.Dragon, },
                },
                new Card { CardId = 130, Name = "Dictate of the Twin Gods", ImageUri = "https://cards.scryfall.io/normal/front/6/1/61d6f304-680c-43ad-9686-61d8b0a0ad14.jpg?1673561141", ConvertedManaCost = 5,
                  ManaCost = new ManaCost { Colorless = 1, White = 0, Blue = 0, Black = 0, Red = 2, Green = 0 },
                  CardTypes = new List<CardType> { CardType.Enchantment, },  CardSubTypes = new List<CardSubType> { },
                },
                new Card { CardId = 131, Name = "Dragon Mage", ImageUri = "https://cards.scryfall.io/normal/front/2/8/2847214c-f435-42db-80db-f3ca8bfb8567.jpg?1674675106", ConvertedManaCost = 7,
                  ManaCost = new ManaCost { Colorless = 1, White = 0, Blue = 0, Black = 0, Red = 2, Green = 0 },
                  CardTypes = new List<CardType> { CardType.Creature, CardType.DragonWizard, },  CardSubTypes = new List<CardSubType> { CardSubType.Dragon, CardSubType.Wizard, },
                },
                new Card { CardId = 132, Name = "Dragon Tempest", ImageUri = "https://cards.scryfall.io/normal/front/1/3/13ad7bb2-e58b-4cd1-9b32-38c7f8589214.jpg?1674675114", ConvertedManaCost = 2,
                  ManaCost = new ManaCost { Colorless = 1, White = 0, Blue = 0, Black = 0, Red = 1, Green = 0 },
                  CardTypes = new List<CardType> { CardType.Enchantment, },  CardSubTypes = new List<CardSubType> { },
                },
                new Card { CardId = 133, Name = "Dragonkin Berserker", ImageUri = "https://cards.scryfall.io/normal/front/d/c/dcfd4840-c524-464a-9519-3fb78e6ee8c5.jpg?1674675122", ConvertedManaCost = 2,
                  ManaCost = new ManaCost { Colorless = 1, White = 0, Blue = 0, Black = 0, Red = 1, Green = 0 },
                  CardTypes = new List<CardType> { CardType.Creature, CardType.HumanBerserker, },  CardSubTypes = new List<CardSubType> { CardSubType.Human, CardSubType.Berserker, },
                },
                new Card { CardId = 134, Name = "Dragonlord's Servant", ImageUri = "https://cards.scryfall.io/normal/front/d/7/d746adc2-5844-424e-af19-c7e80498f106.jpg?1674675131", ConvertedManaCost = 2,
                  ManaCost = new ManaCost { Colorless = 1, White = 0, Blue = 0, Black = 0, Red = 1, Green = 0 },
                  CardTypes = new List<CardType> { CardType.Creature, CardType.GoblinShaman, },  CardSubTypes = new List<CardSubType> { CardSubType.Goblin, CardSubType.Shaman, },
                },
                new Card { CardId = 135, Name = "Dragonmaster Outcast", ImageUri = "https://cards.scryfall.io/normal/front/e/7/e7198cf2-795d-4921-be28-86f208dfe1f3.jpg?1674675140", ConvertedManaCost = 1,
                  ManaCost = new ManaCost { Colorless = 0, White = 0, Blue = 0, Black = 0, Red = 1, Green = 0 },
                  CardTypes = new List<CardType> { CardType.Creature, CardType.HumanShaman, },  CardSubTypes = new List<CardSubType> { CardSubType.Human, CardSubType.Shaman, },
                },
                new Card { CardId = 136, Name = "Dragonspeaker Shaman", ImageUri = "https://cards.scryfall.io/normal/front/9/3/938de396-9701-4737-b913-c3c010f1b142.jpg?1674675148", ConvertedManaCost = 3,
                  ManaCost = new ManaCost { Colorless = 1, White = 0, Blue = 0, Black = 0, Red = 2, Green = 0 },
                  CardTypes = new List<CardType> { CardType.Creature, CardType.HumanBarbarianShaman, },  CardSubTypes = new List<CardSubType> { CardSubType.Human, CardSubType.Barbarian, CardSubType.Shaman, },
                },
                new Card { CardId = 137, Name = "Drakuseth, Maw of Flames", ImageUri = "https://cards.scryfall.io/normal/front/c/8/c8b43b68-ee35-4704-9a0f-1df4a42d3791.jpg?1674675157", ConvertedManaCost = 7,
                  ManaCost = new ManaCost { Colorless = 1, White = 0, Blue = 0, Black = 0, Red = 3, Green = 0 },
                  CardTypes = new List<CardType> { CardType.LegendaryCreature, CardType.Dragon, },  CardSubTypes = new List<CardSubType> { CardSubType.Dragon, },
                },
                new Card { CardId = 138, Name = "Dream Pillager", ImageUri = "https://cards.scryfall.io/normal/front/5/2/5284c6db-82f4-4285-ade3-9b136abcedd2.jpg?1674675165", ConvertedManaCost = 7,
                  ManaCost = new ManaCost { Colorless = 1, White = 0, Blue = 0, Black = 0, Red = 2, Green = 0 },
                  CardTypes = new List<CardType> { CardType.Creature, CardType.Dragon, },  CardSubTypes = new List<CardSubType> { CardSubType.Dragon, },
                },
                new Card { CardId = 139, Name = "Explosion of Riches", ImageUri = "https://cards.scryfall.io/normal/front/e/2/e28ed670-eae0-4a39-bf3d-73b687327f0f.jpg?1674675174", ConvertedManaCost = 6,
                  ManaCost = new ManaCost { Colorless = 1, White = 0, Blue = 0, Black = 0, Red = 1, Green = 0 },
                  CardTypes = new List<CardType> { CardType.Sorcery, },  CardSubTypes = new List<CardSubType> { },
                },
                new Card { CardId = 140, Name = "Fiery Confluence", ImageUri = "https://cards.scryfall.io/normal/front/f/6/f6ff58e0-c938-458b-adea-9aa0b566a19b.jpg?1674675183", ConvertedManaCost = 4,
                  ManaCost = new ManaCost { Colorless = 1, White = 0, Blue = 0, Black = 0, Red = 2, Green = 0 },
                  CardTypes = new List<CardType> { CardType.Sorcery, },  CardSubTypes = new List<CardSubType> { },
                },
                new Card { CardId = 141, Name = "Flameblast Dragon", ImageUri = "https://cards.scryfall.io/normal/front/9/0/90390efc-beca-440e-abee-65c1a29223cb.jpg?1674675191", ConvertedManaCost = 6,
                  ManaCost = new ManaCost { Colorless = 1, White = 0, Blue = 0, Black = 0, Red = 2, Green = 0 },
                  CardTypes = new List<CardType> { CardType.Creature, CardType.Dragon, },  CardSubTypes = new List<CardSubType> { CardSubType.Dragon, },
                },
                new Card { CardId = 142, Name = "Furnace Whelp", ImageUri = "https://cards.scryfall.io/normal/front/3/9/396db1ad-e463-49b7-a4da-24302f771441.jpg?1674675200", ConvertedManaCost = 4,
                  ManaCost = new ManaCost { Colorless = 1, White = 0, Blue = 0, Black = 0, Red = 2, Green = 0 },
                  CardTypes = new List<CardType> { CardType.Creature, CardType.Dragon, },  CardSubTypes = new List<CardSubType> { CardSubType.Dragon, },
                },
                new Card { CardId = 143, Name = "Geode Rager", ImageUri = "https://cards.scryfall.io/normal/front/f/6/f6ba7b25-02bd-4e01-9920-ec84e89250b3.jpg?1674675209", ConvertedManaCost = 6,
                  ManaCost = new ManaCost { Colorless = 1, White = 0, Blue = 0, Black = 0, Red = 2, Green = 0 },
                  CardTypes = new List<CardType> { CardType.Creature, CardType.Elemental, },  CardSubTypes = new List<CardSubType> { CardSubType.Elemental, },
                },
                new Card { CardId = 144, Name = "Guttersnipe", ImageUri = "https://cards.scryfall.io/normal/front/1/e/1e8f9ef5-762f-438f-b06b-9c30c4e364f0.jpg?1674675218", ConvertedManaCost = 3,
                  ManaCost = new ManaCost { Colorless = 1, White = 0, Blue = 0, Black = 0, Red = 1, Green = 0 },
                  CardTypes = new List<CardType> { CardType.Creature, CardType.GoblinShaman, },  CardSubTypes = new List<CardSubType> { CardSubType.Goblin, CardSubType.Shaman, },
                },
                new Card { CardId = 145, Name = "Hate Mirage", ImageUri = "https://cards.scryfall.io/normal/front/e/a/ea074c36-7116-4513-8064-2a12a2257db6.jpg?1674675226", ConvertedManaCost = 4,
                  ManaCost = new ManaCost { Colorless = 1, White = 0, Blue = 0, Black = 0, Red = 1, Green = 0 },
                  CardTypes = new List<CardType> { CardType.Sorcery, },  CardSubTypes = new List<CardSubType> { },
                },
                new Card { CardId = 146, Name = "Hoard-Smelter Dragon", ImageUri = "https://cards.scryfall.io/normal/front/b/4/b4487bbe-2bc4-48d9-8a6f-9b0c7555fb47.jpg?1674675235", ConvertedManaCost = 6,
                  ManaCost = new ManaCost { Colorless = 1, White = 0, Blue = 0, Black = 0, Red = 2, Green = 0 },
                  CardTypes = new List<CardType> { CardType.Creature, CardType.Dragon, },  CardSubTypes = new List<CardSubType> { CardSubType.Dragon, },
                },
                new Card { CardId = 147, Name = "Kazuul, Tyrant of the Cliffs", ImageUri = "https://cards.scryfall.io/normal/front/b/9/b986e9e1-7233-4817-855c-68b7249d00f7.jpg?1674675244", ConvertedManaCost = 5,
                  ManaCost = new ManaCost { Colorless = 1, White = 0, Blue = 0, Black = 0, Red = 2, Green = 0 },
                  CardTypes = new List<CardType> { CardType.LegendaryCreature, CardType.OgreWarrior, },  CardSubTypes = new List<CardSubType> { CardSubType.Ogre, CardSubType.Warrior, },
                },
                new Card { CardId = 148, Name = "Magmaquake", ImageUri = "https://cards.scryfall.io/normal/front/d/d/dd99b254-3830-4543-a8c7-42899dc6fc65.jpg?1674675252", ConvertedManaCost = 2,
                  ManaCost = new ManaCost { Colorless = 0, White = 0, Blue = 0, Black = 0, Red = 2, Green = 0 },
                  CardTypes = new List<CardType> { CardType.Instant, },  CardSubTypes = new List<CardSubType> { },
                },
                new Card { CardId = 149, Name = "Magmatic Force", ImageUri = "https://cards.scryfall.io/normal/front/1/4/146e7071-d4b7-4280-842f-16af580b5b3d.jpg?1674675260", ConvertedManaCost = 8,
                  ManaCost = new ManaCost { Colorless = 1, White = 0, Blue = 0, Black = 0, Red = 3, Green = 0 },
                  CardTypes = new List<CardType> { CardType.Creature, CardType.Elemental, },  CardSubTypes = new List<CardSubType> { CardSubType.Elemental, },
                },
                new Card { CardId = 150, Name = "Mana Geyser", ImageUri = "https://cards.scryfall.io/normal/front/c/9/c9b8b1cf-4dbf-4ddb-ab41-31e482cc573b.jpg?1674675269", ConvertedManaCost = 5,
                  ManaCost = new ManaCost { Colorless = 1, White = 0, Blue = 0, Black = 0, Red = 2, Green = 0 },
                  CardTypes = new List<CardType> { CardType.Sorcery, },  CardSubTypes = new List<CardSubType> { },
                },
                new Card { CardId = 151, Name = "Mordant Dragon", ImageUri = "https://cards.scryfall.io/normal/front/a/8/a83a2fe7-36df-4a38-8dd3-605eeb5f58f1.jpg?1673561310", ConvertedManaCost = 6,
                  ManaCost = new ManaCost { Colorless = 1, White = 0, Blue = 0, Black = 0, Red = 3, Green = 0 },
                  CardTypes = new List<CardType> { CardType.Creature, CardType.Dragon, },  CardSubTypes = new List<CardSubType> { CardSubType.Dragon, },
                },
                new Card { CardId = 152, Name = "Provoke the Trolls", ImageUri = "https://cards.scryfall.io/normal/front/9/6/964ae341-64eb-4ac1-9fb0-7243d5fe744d.jpg?1674675277", ConvertedManaCost = 4,
                  ManaCost = new ManaCost { Colorless = 1, White = 0, Blue = 0, Black = 0, Red = 1, Green = 0 },
                  CardTypes = new List<CardType> { CardType.Instant, },  CardSubTypes = new List<CardSubType> { },
                },
                new Card { CardId = 153, Name = "Rapacious Dragon", ImageUri = "https://cards.scryfall.io/normal/front/a/f/af7d2077-c108-4cb6-af56-3815991439b7.jpg?1674675286", ConvertedManaCost = 5,
                  ManaCost = new ManaCost { Colorless = 1, White = 0, Blue = 0, Black = 0, Red = 1, Green = 0 },
                  CardTypes = new List<CardType> { CardType.Creature, CardType.Dragon, },  CardSubTypes = new List<CardSubType> { CardSubType.Dragon, },
                },
                new Card { CardId = 154, Name = "Runehorn Hellkite", ImageUri = "https://cards.scryfall.io/normal/front/9/3/932504ec-274e-49e6-ac51-a8ec362e83d5.jpg?1674675294", ConvertedManaCost = 6,
                  ManaCost = new ManaCost { Colorless = 1, White = 0, Blue = 0, Black = 0, Red = 1, Green = 0 },
                  CardTypes = new List<CardType> { CardType.Creature, CardType.Dragon, },  CardSubTypes = new List<CardSubType> { CardSubType.Dragon, },
                },
                new Card { CardId = 155, Name = "Sarkhan, the Dragonspeaker", ImageUri = "https://cards.scryfall.io/normal/front/e/6/e653b95e-43c8-4cd6-a094-b2cd22d0eda2.jpg?1674675302", ConvertedManaCost = 5,
                  ManaCost = new ManaCost { Colorless = 1, White = 0, Blue = 0, Black = 0, Red = 2, Green = 0 },
                  CardTypes = new List<CardType> { CardType.LegendaryPlaneswalker, CardType.Sarkhan, },  CardSubTypes = new List<CardSubType> { CardSubType.Sarkhan, },
                },
                new Card { CardId = 156, Name = "Scourge of Valkas", ImageUri = "https://cards.scryfall.io/normal/front/0/2/02ba0244-b7fa-4090-a1ac-1ba762dd8cc3.jpg?1674675310", ConvertedManaCost = 5,
                  ManaCost = new ManaCost { Colorless = 1, White = 0, Blue = 0, Black = 0, Red = 3, Green = 0 },
                  CardTypes = new List<CardType> { CardType.Creature, CardType.Dragon, },  CardSubTypes = new List<CardSubType> { CardSubType.Dragon, },
                },
                new Card { CardId = 157, Name = "Spit Flame", ImageUri = "https://cards.scryfall.io/normal/front/4/9/49fed954-0341-4a06-ae34-71e7d8c779ab.jpg?1674675318", ConvertedManaCost = 3,
                  ManaCost = new ManaCost { Colorless = 1, White = 0, Blue = 0, Black = 0, Red = 1, Green = 0 },
                  CardTypes = new List<CardType> { CardType.Instant, },  CardSubTypes = new List<CardSubType> { },
                },
                new Card { CardId = 158, Name = "Sunbird's Invocation", ImageUri = "https://cards.scryfall.io/normal/front/8/0/80ca8daf-0898-4740-977b-6a145721f667.jpg?1674675327", ConvertedManaCost = 6,
                  ManaCost = new ManaCost { Colorless = 1, White = 0, Blue = 0, Black = 0, Red = 1, Green = 0 },
                  CardTypes = new List<CardType> { CardType.Enchantment, },  CardSubTypes = new List<CardSubType> { },
                },
                new Card { CardId = 159, Name = "Sweltering Suns", ImageUri = "https://cards.scryfall.io/normal/front/7/4/7414b8da-abbe-4fba-afaf-2c9ff650a429.jpg?1674675334", ConvertedManaCost = 3,
                  ManaCost = new ManaCost { Colorless = 1, White = 0, Blue = 0, Black = 0, Red = 2, Green = 0 },
                  CardTypes = new List<CardType> { CardType.Sorcery, },  CardSubTypes = new List<CardSubType> { },
                },
                new Card { CardId = 160, Name = "Tectonic Giant", ImageUri = "https://cards.scryfall.io/normal/front/4/4/449c7351-ff39-4597-9f81-b8665f76bce7.jpg?1674675343", ConvertedManaCost = 4,
                  ManaCost = new ManaCost { Colorless = 1, White = 0, Blue = 0, Black = 0, Red = 2, Green = 0 },
                  CardTypes = new List<CardType> { CardType.Creature, CardType.ElementalGiant, },  CardSubTypes = new List<CardSubType> { CardSubType.Elemental, CardSubType.Giant, },
                },
                new Card { CardId = 161, Name = "Thermo-Alchemist", ImageUri = "https://cards.scryfall.io/normal/front/9/8/98c79cd4-c084-4c01-beeb-70fb12dd6e69.jpg?1674675351", ConvertedManaCost = 2,
                  ManaCost = new ManaCost { Colorless = 1, White = 0, Blue = 0, Black = 0, Red = 1, Green = 0 },
                  CardTypes = new List<CardType> { CardType.Creature, CardType.HumanShaman, },  CardSubTypes = new List<CardSubType> { CardSubType.Human, CardSubType.Shaman, },
                },
                new Card { CardId = 162, Name = "Thunderbreak Regent", ImageUri = "https://cards.scryfall.io/normal/front/a/9/a985687c-7a3a-4de2-9af3-450cb665d523.jpg?1674675360", ConvertedManaCost = 4,
                  ManaCost = new ManaCost { Colorless = 1, White = 0, Blue = 0, Black = 0, Red = 2, Green = 0 },
                  CardTypes = new List<CardType> { CardType.Creature, CardType.Dragon, },  CardSubTypes = new List<CardSubType> { CardSubType.Dragon, },
                },
                new Card { CardId = 163, Name = "Thundermaw Hellkite", ImageUri = "https://cards.scryfall.io/normal/front/7/a/7a517c33-b516-4ad9-8cd8-d2ca27310252.jpg?1674675369", ConvertedManaCost = 5,
                  ManaCost = new ManaCost { Colorless = 1, White = 0, Blue = 0, Black = 0, Red = 2, Green = 0 },
                  CardTypes = new List<CardType> { CardType.Creature, CardType.Dragon, },  CardSubTypes = new List<CardSubType> { CardSubType.Dragon, },
                },
                new Card { CardId = 164, Name = "Tyrant's Familiar", ImageUri = "https://cards.scryfall.io/normal/front/4/f/4f0c7f3b-337e-4b61-8ab9-5e67a0979a9a.jpg?1674675378", ConvertedManaCost = 7,
                  ManaCost = new ManaCost { Colorless = 1, White = 0, Blue = 0, Black = 0, Red = 2, Green = 0 },
                  CardTypes = new List<CardType> { CardType.Creature, CardType.Dragon, },  CardSubTypes = new List<CardSubType> { CardSubType.Dragon, },
                },
                new Card { CardId = 165, Name = "Unleash Fury", ImageUri = "https://cards.scryfall.io/normal/front/0/4/04b1739c-bc65-482c-81fd-fa08d6f29fcd.jpg?1674675389", ConvertedManaCost = 2,
                  ManaCost = new ManaCost { Colorless = 1, White = 0, Blue = 0, Black = 0, Red = 1, Green = 0 },
                  CardTypes = new List<CardType> { CardType.Instant, },  CardSubTypes = new List<CardSubType> { },
                },
                new Card { CardId = 166, Name = "Vandalblast", ImageUri = "https://cards.scryfall.io/normal/front/7/1/71eb87ef-7e79-4370-a367-f8960cfe188e.jpg?1674675398", ConvertedManaCost = 1,
                  ManaCost = new ManaCost { Colorless = 0, White = 0, Blue = 0, Black = 0, Red = 1, Green = 0 },
                  CardTypes = new List<CardType> { CardType.Sorcery, },  CardSubTypes = new List<CardSubType> { },
                },
                new Card { CardId = 167, Name = "Verix Bladewing", ImageUri = "https://cards.scryfall.io/normal/front/3/5/359be9e6-0770-43e3-853c-95e5317e9d30.jpg?1674675406", ConvertedManaCost = 4,
                  ManaCost = new ManaCost { Colorless = 1, White = 0, Blue = 0, Black = 0, Red = 2, Green = 0 },
                  CardTypes = new List<CardType> { CardType.LegendaryCreature, CardType.Dragon, },  CardSubTypes = new List<CardSubType> { CardSubType.Dragon, },
                },
                new Card { CardId = 168, Name = "Wild Ricochet", ImageUri = "https://cards.scryfall.io/normal/front/e/c/ecbe8717-07a1-4145-9cd4-b98b145c2d4c.jpg?1674675414", ConvertedManaCost = 4,
                  ManaCost = new ManaCost { Colorless = 1, White = 0, Blue = 0, Black = 0, Red = 2, Green = 0 },
                  CardTypes = new List<CardType> { CardType.Instant, },  CardSubTypes = new List<CardSubType> { },
                },
                new Card { CardId = 169, Name = "Wildfire Devils", ImageUri = "https://cards.scryfall.io/normal/front/3/c/3c876360-3608-422a-b709-84b32be8daa0.jpg?1674675422", ConvertedManaCost = 4,
                  ManaCost = new ManaCost { Colorless = 1, White = 0, Blue = 0, Black = 0, Red = 1, Green = 0 },
                  CardTypes = new List<CardType> { CardType.Creature, CardType.Devil, },  CardSubTypes = new List<CardSubType> { CardSubType.Devil, },
                },
                new Card { CardId = 170, Name = "Avacyn's Pilgrim", ImageUri = "https://cards.scryfall.io/normal/front/4/1/418bf817-433a-4d9a-bea7-827014184269.jpg?1674675432", ConvertedManaCost = 1,
                  ManaCost = new ManaCost { Colorless = 0, White = 0, Blue = 0, Black = 0, Red = 0, Green = 1 },
                  CardTypes = new List<CardType> { CardType.Creature, CardType.HumanMonk, },  CardSubTypes = new List<CardSubType> { CardSubType.Human, CardSubType.Monk, },
                },
                new Card { CardId = 171, Name = "Beast Within", ImageUri = "https://cards.scryfall.io/normal/front/f/b/fb961f73-e352-4373-b2ae-1730b654640c.jpg?1674675440", ConvertedManaCost = 3,
                  ManaCost = new ManaCost { Colorless = 1, White = 0, Blue = 0, Black = 0, Red = 0, Green = 1 },
                  CardTypes = new List<CardType> { CardType.Instant, },  CardSubTypes = new List<CardSubType> { },
                },
                new Card { CardId = 172, Name = "Blossoming Defense", ImageUri = "https://cards.scryfall.io/normal/front/b/f/bf65fcd0-5f4e-4e65-ac86-2f14d5c7d527.jpg?1674675448", ConvertedManaCost = 1,
                  ManaCost = new ManaCost { Colorless = 0, White = 0, Blue = 0, Black = 0, Red = 0, Green = 1 },
                  CardTypes = new List<CardType> { CardType.Instant, },  CardSubTypes = new List<CardSubType> { },
                },
                new Card { CardId = 173, Name = "Champion of Lambholt", ImageUri = "https://cards.scryfall.io/normal/front/8/1/812c252d-9947-4bd4-8097-670be91c338e.jpg?1674675457", ConvertedManaCost = 3,
                  ManaCost = new ManaCost { Colorless = 1, White = 0, Blue = 0, Black = 0, Red = 0, Green = 2 },
                  CardTypes = new List<CardType> { CardType.Creature, CardType.HumanWarrior, },  CardSubTypes = new List<CardSubType> { CardSubType.Human, CardSubType.Warrior, },
                },
                new Card { CardId = 174, Name = "Citanul Hierophants", ImageUri = "https://cards.scryfall.io/normal/front/7/9/79c3190a-a18b-41b6-9626-5fd12edb4e36.jpg?1673569713", ConvertedManaCost = 4,
                  ManaCost = new ManaCost { Colorless = 1, White = 0, Blue = 0, Black = 0, Red = 0, Green = 1 },
                  CardTypes = new List<CardType> { CardType.Creature, CardType.HumanDruid, },  CardSubTypes = new List<CardSubType> { CardSubType.Human, CardSubType.Druid, },
                },
                new Card { CardId = 175, Name = "Atarka, World Render", ImageUri = "https://cards.scryfall.io/normal/front/7/1/719f172b-f9ad-4960-af66-757eb54147f6.jpg?1683836596", ConvertedManaCost = 7,
                  ManaCost = new ManaCost { Colorless = 1, White = 0, Blue = 0, Black = 0, Red = 1, Green = 1 },
                  CardTypes = new List<CardType> { CardType.LegendaryCreature, CardType.Dragon, },  CardSubTypes = new List<CardSubType> { CardSubType.Dragon, },
                },
                new Card { CardId = 176, Name = "Emmara, Soul of the Accord", ImageUri = "https://cards.scryfall.io/normal/front/e/8/e8510a1e-62ca-462c-b036-d1312729f27d.jpg?1683836594", ConvertedManaCost = 2,
                  ManaCost = new ManaCost { Colorless = 0, White = 1, Blue = 0, Black = 0, Red = 0, Green = 1 },
                  CardTypes = new List<CardType> { CardType.LegendaryCreature, CardType.ElfCleric, },  CardSubTypes = new List<CardSubType> { CardSubType.Elf, CardSubType.Cleric, },
                },
                new Card { CardId = 177, Name = "Gisa and Geralf", ImageUri = "https://cards.scryfall.io/normal/front/4/d/4d8fd87c-caf7-402e-b543-e35ba3007bcb.jpg?1683836591", ConvertedManaCost = 4,
                  ManaCost = new ManaCost { Colorless = 1, White = 0, Blue = 1, Black = 1, Red = 0, Green = 0 },
                  CardTypes = new List<CardType> { CardType.LegendaryCreature, CardType.HumanWizard, },  CardSubTypes = new List<CardSubType> { CardSubType.Human, CardSubType.Wizard, },
                },
                new Card { CardId = 178, Name = "Isperia, Supreme Judge", ImageUri = "https://cards.scryfall.io/normal/front/d/e/de3278de-a045-4290-b05f-3b19e7055091.jpg?1683836628", ConvertedManaCost = 6,
                  ManaCost = new ManaCost { Colorless = 1, White = 2, Blue = 2, Black = 0, Red = 0, Green = 0 },
                  CardTypes = new List<CardType> { CardType.LegendaryCreature, CardType.Sphinx, },  CardSubTypes = new List<CardSubType> { CardSubType.Sphinx, },
                },
                new Card { CardId = 179, Name = "Kardur, Doomscourge", ImageUri = "https://cards.scryfall.io/normal/front/1/9/19e4d494-e8b3-4ae2-93e3-70c65ab90f15.jpg?1683836583", ConvertedManaCost = 4,
                  ManaCost = new ManaCost { Colorless = 1, White = 0, Blue = 0, Black = 1, Red = 1, Green = 0 },
                  CardTypes = new List<CardType> { CardType.LegendaryCreature, CardType.DemonBerserker, },  CardSubTypes = new List<CardSubType> { CardSubType.Demon, CardSubType.Berserker, },
                },
                new Card { CardId = 180, Name = "Ajani, Caller of the Pride", ImageUri = "https://cards.scryfall.io/normal/front/6/1/6121cf58-93d0-4430-a4a2-91778ba65249.jpg?1673560015", ConvertedManaCost = 3,
                  ManaCost = new ManaCost { Colorless = 1, White = 2, Blue = 0, Black = 0, Red = 0, Green = 0 },
                  CardTypes = new List<CardType> { CardType.LegendaryPlaneswalker, CardType.Ajani, },  CardSubTypes = new List<CardSubType> { CardSubType.Ajani, },
                },
                new Card { CardId = 181, Name = "Archon of Redemption", ImageUri = "https://cards.scryfall.io/normal/front/2/2/2243270a-2e7c-4239-af2e-9b6b47124237.jpg?1674674027", ConvertedManaCost = 5,
                  ManaCost = new ManaCost { Colorless = 1, White = 2, Blue = 0, Black = 0, Red = 0, Green = 0 },
                  CardTypes = new List<CardType> { CardType.Creature, CardType.Archon, },  CardSubTypes = new List<CardSubType> { CardSubType.Archon, },
                },
                new Card { CardId = 182, Name = "Aven Gagglemaster", ImageUri = "https://cards.scryfall.io/normal/front/a/0/a07568b2-5a1f-4aaf-bd71-57b41bae925d.jpg?1674674036", ConvertedManaCost = 5,
                  ManaCost = new ManaCost { Colorless = 1, White = 2, Blue = 0, Black = 0, Red = 0, Green = 0 },
                  CardTypes = new List<CardType> { CardType.Creature, CardType.BirdWarrior, },  CardSubTypes = new List<CardSubType> { CardSubType.Bird, CardSubType.Warrior, },
                },
                new Card { CardId = 183, Name = "Banishing Light", ImageUri = "https://cards.scryfall.io/normal/front/0/7/078a222f-2efb-44ed-95d8-6435bd026611.jpg?1674674046", ConvertedManaCost = 3,
                  ManaCost = new ManaCost { Colorless = 1, White = 1, Blue = 0, Black = 0, Red = 0, Green = 0 },
                  CardTypes = new List<CardType> { CardType.Enchantment, },  CardSubTypes = new List<CardSubType> { },
                },
                new Card { CardId = 184, Name = "Cartographer's Hawk", ImageUri = "https://cards.scryfall.io/normal/front/c/7/c72102e8-3bcf-4164-a41a-43e3cf1b4b72.jpg?1674674056", ConvertedManaCost = 2,
                  ManaCost = new ManaCost { Colorless = 1, White = 1, Blue = 0, Black = 0, Red = 0, Green = 0 },
                  CardTypes = new List<CardType> { CardType.Creature, CardType.Bird, },  CardSubTypes = new List<CardSubType> { CardSubType.Bird, },
                },
                new Card { CardId = 185, Name = "Citywide Bust", ImageUri = "https://cards.scryfall.io/normal/front/c/2/c249e9db-41a7-4da8-99b3-d7854c538713.jpg?1674674065", ConvertedManaCost = 3,
                  ManaCost = new ManaCost { Colorless = 1, White = 2, Blue = 0, Black = 0, Red = 0, Green = 0 },
                  CardTypes = new List<CardType> { CardType.Sorcery, },  CardSubTypes = new List<CardSubType> { },
                },
                new Card { CardId = 186, Name = "Cleansing Nova", ImageUri = "https://cards.scryfall.io/normal/front/3/1/31619741-1899-4503-bc1c-176a3248df86.jpg?1674674073", ConvertedManaCost = 5,
                  ManaCost = new ManaCost { Colorless = 1, White = 2, Blue = 0, Black = 0, Red = 0, Green = 0 },
                  CardTypes = new List<CardType> { CardType.Sorcery, },  CardSubTypes = new List<CardSubType> { },
                },
                new Card { CardId = 187, Name = "Commander's Insignia", ImageUri = "https://cards.scryfall.io/normal/front/1/2/12b2b04b-27d1-4b5d-9bd6-9678f203cf20.jpg?1674674082", ConvertedManaCost = 4,
                  ManaCost = new ManaCost { Colorless = 1, White = 2, Blue = 0, Black = 0, Red = 0, Green = 0 },
                  CardTypes = new List<CardType> { CardType.Enchantment, },  CardSubTypes = new List<CardSubType> { },
                },
                new Card { CardId = 188, Name = "Conclave Tribunal", ImageUri = "https://cards.scryfall.io/normal/front/1/d/1dc26b58-1b10-41a3-8155-bbc8f189de15.jpg?1674674092", ConvertedManaCost = 4,
                  ManaCost = new ManaCost { Colorless = 1, White = 1, Blue = 0, Black = 0, Red = 0, Green = 0 },
                  CardTypes = new List<CardType> { CardType.Enchantment, },  CardSubTypes = new List<CardSubType> { },
                },
                new Card { CardId = 189, Name = "Condemn", ImageUri = "https://cards.scryfall.io/normal/front/8/5/8554c243-b300-47c2-8dbb-f6a054b894f9.jpg?1674674100", ConvertedManaCost = 1,
                  ManaCost = new ManaCost { Colorless = 0, White = 1, Blue = 0, Black = 0, Red = 0, Green = 0 },
                  CardTypes = new List<CardType> { CardType.Instant, },  CardSubTypes = new List<CardSubType> { },
                },
                new Card { CardId = 190, Name = "Crush Contraband", ImageUri = "https://cards.scryfall.io/normal/front/0/b/0bdf1bc0-116e-4fd0-bbc8-1e284b92d7c0.jpg?1674674111", ConvertedManaCost = 4,
                  ManaCost = new ManaCost { Colorless = 1, White = 1, Blue = 0, Black = 0, Red = 0, Green = 0 },
                  CardTypes = new List<CardType> { CardType.Instant, },  CardSubTypes = new List<CardSubType> { },
                },
                new Card { CardId = 191, Name = "Dawn of Hope", ImageUri = "https://cards.scryfall.io/normal/front/a/0/a02540fc-42ee-4f61-99c8-efdd1a70373c.jpg?1674674119", ConvertedManaCost = 2,
                  ManaCost = new ManaCost { Colorless = 1, White = 1, Blue = 0, Black = 0, Red = 0, Green = 0 },
                  CardTypes = new List<CardType> { CardType.Enchantment, },  CardSubTypes = new List<CardSubType> { },
                },
                new Card { CardId = 192, Name = "Devouring Light", ImageUri = "https://cards.scryfall.io/normal/front/a/2/a22f129b-18a6-4328-aa83-1079be811dcf.jpg?1674674128", ConvertedManaCost = 3,
                  ManaCost = new ManaCost { Colorless = 1, White = 2, Blue = 0, Black = 0, Red = 0, Green = 0 },
                  CardTypes = new List<CardType> { CardType.Instant, },  CardSubTypes = new List<CardSubType> { },
                },
                new Card { CardId = 193, Name = "Dictate of Heliod", ImageUri = "https://cards.scryfall.io/normal/front/f/e/fe2f3830-d822-4cb5-a88a-df5c5b9020a4.jpg?1674674137", ConvertedManaCost = 5,
                  ManaCost = new ManaCost { Colorless = 1, White = 2, Blue = 0, Black = 0, Red = 0, Green = 0 },
                  CardTypes = new List<CardType> { CardType.Enchantment, },  CardSubTypes = new List<CardSubType> { },
                },
                new Card { CardId = 194, Name = "Disenchant", ImageUri = "https://cards.scryfall.io/normal/front/d/3/d32a8448-de76-4d1e-a3dd-8fffeab71216.jpg?1674674145", ConvertedManaCost = 2,
                  ManaCost = new ManaCost { Colorless = 1, White = 1, Blue = 0, Black = 0, Red = 0, Green = 0 },
                  CardTypes = new List<CardType> { CardType.Instant, },  CardSubTypes = new List<CardSubType> { },
                },
                new Card { CardId = 195, Name = "Emeria Angel", ImageUri = "https://cards.scryfall.io/normal/front/a/3/a30852be-473c-40f3-98bf-2d48fcde0239.jpg?1674674154", ConvertedManaCost = 4,
                  ManaCost = new ManaCost { Colorless = 1, White = 2, Blue = 0, Black = 0, Red = 0, Green = 0 },
                  CardTypes = new List<CardType> { CardType.Creature, CardType.Angel, },  CardSubTypes = new List<CardSubType> { CardSubType.Angel, },
                },
                new Card { CardId = 196, Name = "Felidar Retreat", ImageUri = "https://cards.scryfall.io/normal/front/7/3/73febb87-d56b-4214-b429-a606f671e992.jpg?1674674163", ConvertedManaCost = 4,
                  ManaCost = new ManaCost { Colorless = 1, White = 1, Blue = 0, Black = 0, Red = 0, Green = 0 },
                  CardTypes = new List<CardType> { CardType.Enchantment, },  CardSubTypes = new List<CardSubType> { },
                },
                new Card { CardId = 197, Name = "Generous Gift", ImageUri = "https://cards.scryfall.io/normal/front/c/d/cd0f77d1-dd28-41c2-a508-4a8c9e3262ef.jpg?1674674172", ConvertedManaCost = 3,
                  ManaCost = new ManaCost { Colorless = 1, White = 1, Blue = 0, Black = 0, Red = 0, Green = 0 },
                  CardTypes = new List<CardType> { CardType.Instant, },  CardSubTypes = new List<CardSubType> { },
                },
                new Card { CardId = 198, Name = "Gideon Jura", ImageUri = "https://cards.scryfall.io/normal/front/d/f/df0d1217-4d83-4292-80e2-f2d86e82aae4.jpg?1674674181", ConvertedManaCost = 5,
                  ManaCost = new ManaCost { Colorless = 1, White = 2, Blue = 0, Black = 0, Red = 0, Green = 0 },
                  CardTypes = new List<CardType> { CardType.LegendaryPlaneswalker, CardType.Gideon, },  CardSubTypes = new List<CardSubType> { CardSubType.Gideon, },
                },
                new Card { CardId = 199, Name = "Hanged Executioner", ImageUri = "https://cards.scryfall.io/normal/front/e/b/eb405cb1-3643-417c-b27f-4b6c3dca3a96.jpg?1674674190", ConvertedManaCost = 3,
                  ManaCost = new ManaCost { Colorless = 1, White = 1, Blue = 0, Black = 0, Red = 0, Green = 0 },
                  CardTypes = new List<CardType> { CardType.Creature, CardType.Spirit, },  CardSubTypes = new List<CardSubType> { CardSubType.Spirit, },
                },
                new Card { CardId = 200, Name = "Hour of Reckoning", ImageUri = "https://cards.scryfall.io/normal/front/9/1/91961188-da2e-4ba5-b938-154719ea0659.jpg?1674674200", ConvertedManaCost = 7,
                  ManaCost = new ManaCost { Colorless = 1, White = 3, Blue = 0, Black = 0, Red = 0, Green = 0 },
                  CardTypes = new List<CardType> { CardType.Sorcery, },  CardSubTypes = new List<CardSubType> { },
                }
            };
        }

        public Card AddCard(Card card)
        {
            cards.Add(card);

            return card;
        }

        public ICollection<Card> GetAllCards() => cards;
    }
}
